### ISSUE TITLE
Ubuntu 22.04 headless init script fails

### ISSUE THREAD

**Issue by jl-678** [FoldingAtHome/fah-client-bastet#101]
The subject says it all.  The init script is based on this file: /etc/int.d/FAHClient.  Here is the output:

```
debian@<hostname>:/etc/init.d$ sudo ./FAHClient start
Starting fahclient ... FAIL
```

Looking at the file, the problem is the code snippet below.  I am not familiar enough with BASH to troubleshoot it.

```
    if wait_for_log_change "$LOG_STATUS" $pid; then
        echo "OK"
    else
        echo "FAIL"
        exit 1
    fi  
```

**Comment by jl-678** [comment]
Update - I reinstalled fah-client on a different system and noted that there is a services file there.  Not sure why the original system did not have one.

**Comment by kbernhagen** [comment]
The init.d script is used by v7.
The v8 installer should maybe remove it.
I believe the v8 guide (which few read) says to uninstall v7 first.

**Comment by jl-678** [comment]
I did remove v7 as you cannot have both. Evidently, the uninstaller did not remove the v7 init.d file. I also noticed that I did not have a service file; I am not sure why. That said, the other machines I recently built had one and so I assume that it must have been something specific to me.

**Comment by kbernhagen** [comment]
Maybe you used the tarball on that machine?

Anyway, the v8 installer should remove the old service and any other cruft.

The v7 uninstal can't be updated without another v7 release.
