### ISSUE TITLE
Error "No Matching Core" in v8 beta

### ISSUE THREAD

**Issue by jl-678** [FoldingAtHome/fah-client-bastet#103]
I wrote a [thread about this](https://foldingforum.org/viewtopic.php?p=358725) on the beta forum.  Basically, I am seeing this error in the v8 client on some older hosts.  I first thought that this was due to the age of these CPUs, but when I installed v7 it happily accepted them and started folding.

**Comment by jl-678** [comment]
Quick update: I received the following core in v7. I am not sure why I am not seeing this in v8 beta.

`21:38:57:WU00:FS00:Running FahCore: /usr/bin/FAHCoreWrapper /var/lib/fahclient/cores/cores.foldingathome.org/lin/64bit-sse2/a8-0.0.12/Core_a8.fah/FahCore_a8 -dir 00 -suffix 01 -version 704 -lifeline 1845 -checkpoint 15`

**Comment by jcoffland** [comment]
This should be fixed now.  There was a missing configuration entry on the AS.  Thanks for the report.
