### ISSUE TITLE
Allow syncing settings across all peers

### ISSUE THREAD

**Issue by jl-678** [FoldingAtHome/fah-client-bastet#104]
While the GUI shows WUs and progress on one screen, it does not seem to sync any settings. If you have multiple systems and want to use a common username, group, passkey, and cause, you have to manually set it on each peer.

**Suggestion:**
Add a checkbox next to the username, group, passkey, and cause fields which you could call "Synchronize with peers."  When checked, this would push these data points to every peer automatically. This provides a nice benefit since you can change any of this information in one place knowing that it will affect all systems.  By using a checkbox, you allow for selective sync so that you can have matching, usernames, groups, and passkey, for example, while still having separate causes.

**Comment by jcoffland** [comment]
This is possible now with F@H accounts.
