### ISSUE TITLE
PPD not in initial json output from websocket for CPU WUs

### ISSUE THREAD

**Issue by alexatkinuk** [FoldingAtHome/fah-client-bastet#105]
PPD appears to be reported for GPU WUs but is not being shown for CPU only WUs.

**Comment by kbernhagen** [comment]
PPD is an estimate which should appear after a couple percent of work is done. For any WU type.

**Comment by kbernhagen** [comment]
If you have a passkey set, the client assumes you have qualified for bonus points.

**Comment by alexatkinuk** [comment]
`{
  "units": [
    {
      "number": 19,
      "group": "",
      "cpus": 3,
      "gpus": [],
      "state": "RUN",
      "paused": false,
      "id": "TA1oaSOdVx3bDlorYPJZ1YL6IfhvkIHQ2eEDoJMGJE4",
      "progress": 0.709,
      "assignment": {
        "time": "2023-01-30T21:59:23Z",
        "ws": "vav19.fah.temple.edu",
        "port": 443,
        "project": 16999,
        "deadline": 432000,
        "timeout": 259200,
        "credit": 3540,
        "cpus": 3,
        "core": {"type": "0xa8", "url": "https://cores.foldingathome.org/fahcore-a8-lin-64bit-avx2_256-0.0.12.tar.bz2", "sha256": "5d81e2df84fb0857e9804ce4c263e412d632b0e7c65bada542b608f1f8a2f204"}
      },
      "wu": {
        "time": "2023-01-30T21:59:23Z",
        "cs": ["129.32.209.205", "129.32.209.203", "129.32.209.207", "129.32.209.204", "129.32.209.200", "128.174.73.78", "ds01.scs.illinois.edu", "129.32.209.201", "129.32.209.206"],
        "server": 2166411722,
        "run": 108,
        "clone": 84,
        "gen": 199,
        "sha256": "61lsbX3z1SSJN75Zbyisz6g89ZUWIv/rZs0c8JCby2s="
      },
      "eta": "1 hour 41 mins",
      "frames": 71,
      "run-time": 10181
    },
    {
      "number": 20,
      "group": "",
      "cpus": 1,
      "gpus": ["gpu:01:00:00"],
      "state": "RUN",
      "paused": false,
      "id": "LZUj8u79IZE4plS4Z1wnZqjLNV80joXElEjhZefvKk0",
      "progress": 0.942,
      "assignment": {
        "time": "2023-01-31T00:49:04Z",
        "ws": "vav19.fah.temple.edu",
        "port": 443,
        "project": 18447,
        "deadline": 172800,
        "timeout": 129600,
        "credit": 31336,
        "cpus": 1,
        "min_cpus": 1,
        "max_cpus": 1,
        "gpus": ["gpu:01:00:00"],
        "core": {"type": "0x22", "url": "https://cores.foldingathome.org/openmm-core-22/fahcore-22-linux-64bit-release-0.0.20.tar.bz2", "sha256": "b23275a4d9685abadd1b8fb583b31d9147eae730d4f054ae5f70aa9aad754c7f"}
      },
      "wu": {
        "time": "2023-01-31T00:49:04Z",
        "cs": ["129.32.209.205", "129.32.209.203", "129.32.209.207", "129.32.209.204", "129.32.209.200", "128.174.73.78", "ds01.scs.illinois.edu", "129.32.209.201", "129.32.209.206"],
        "server": 2166411722,
        "run": 0,
        "clone": 20,
        "gen": 939,
        "sha256": "UMQS8Wl9E5HpDqdH6SciuHomg5/iWdKl3yLPeRJUhkc="
      },
      "eta": "4 mins 46 secs",
      "ppd": 2764800,
      "frames": 94
    }
  ],`

As you can see, it showing up for the GPU unit but not the CPU only one.

**Comment by kbernhagen** [comment]
Yep. You’re right. 
Interesting that it maybe has “run-time” instead. That sounds like something used to calculate ppd.

**Comment by alexatkinuk** [comment]
I was wondering that, but either way the output should be consistent.  Hopefully they will add PPD into the WebUI and HAVE to fix this as part of that.

**Comment by jcoffland** [comment]
``ppd`` is only reported if it's non-zero.  ``run-time`` is only reported after a WU has run and paused.  It's a running total of the amount of time in seconds that the WU has been running.  It's used for computing ``eta``.

**Comment by alexatkinuk** [comment]
But WHY would the PPD be zero?  Bug in the CPU core?

**Comment by jcoffland** [comment]
PPD is just a prediction.  It's zero when there's not yet enough information.

**Comment by alexatkinuk** [comment]
The issue is its NEVER reported for CPU WUs, although I haven't checked the latest build.
