### ISSUE TITLE
CPUid not being shown in the list for Windows

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#108]
[Reported by bollix47 in Slack]
It looks like an issue for Windows only for the CPUid not being shown in the list. FAH v8 on Linux creates a CPUid for the PC (same for either Resource Group), but FAH v8 on Windows 10 didn't.
Linux: https://apps.foldingathome.org/wu#project=18449&run=3&clone=358&gen=474  -->  (/RG1) the CPUid (1689DD85D0E798F8) is in the list: https://apps.foldingathome.org/cpu?q=Hou5e_ALL_15k84jUoNPb1kodGvYtKDHiBPRX4Qs3kx8
Linux (same PC): https://apps.foldingathome.org/wu#project=18448&run=11&clone=426&gen=304  -->  (/RG2) the CPUid (1689DD85D0E798F8) is in the list

Linux: https://apps.foldingathome.org/wu#project=18449&run=2&clone=186&gen=323  -->  (/RG1) the CPUid (6091A93230714E8C) is in the list
Linux(same PC): https://apps.foldingathome.org/wu#project=18213&run=34990&clone=1&gen=2  -->  (/RG2) the CPUid (6091A93230714E8C) is in the list

Windows 10: https://apps.foldingathome.org/wu#project=18601&run=17064&clone=3&gen=31  -->  the CPUid (F51AEE021249D66E) is not in the list
Windows 10 (Same PC, but newer FAH v8 install): https://apps.foldingathome.org/wu#project=18601&run=14849&clone=4&gen=19  -->  the CPUid (DBD3C325D4AA0117) is not in the list
Windows 10 (Same PC, but different username for testing): https://apps.foldingathome.org/wu#project=18449&run=4&clone=418&gen=245  -->  the CPUid (DBD3C325D4AA0117) is not in the list: https://apps.foldingathome.org/cpu?q=Hou5e  This username has folded a few WUs recently https://folding.extremeoverclocking.com/user_summary.php?s=&u=1297534

**Comment by jcoffland** [comment]
Is it possible these are from older clients?  An issue with the CPUID was fixed in v8.1.7.

**Comment by bollix47** [comment]
In my case I'm using v8.1.11

**Comment by Hou5e** [comment]
I'm using v8.1.11 in the examples listed, except the first Windows example for CPUid (F51AEE021249D66E) was from FAH v8.1.6.

**Comment by jcoffland** [comment]
This should be fixed now.  The problem was that v8 reports the OS as WIN64 whereas v7 always reports it as WIN32.  The DB was lacking an entry for OS type WIN64.  It may take a few minutes for the web cache to clear in some cases.
