### ISSUE TITLE
Separate CPUids in FAH v8 for each Resource Group

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#109]
Resource Groups seem like they should have separate CPUids in FAH v8?

FAH v8 uses the same CPUid for each Resource Group on the same PC:
https://apps.foldingathome.org/wu#project=18449&run=2&clone=186&gen=323  -->  (/RG1) CPUid: 6091A93230714E8C
https://apps.foldingathome.org/wu#project=18213&run=34990&clone=1&gen=2  -->  (/RG2) the CPUid: 6091A93230714E8C

FAH v7 makes a separate CPUid for each slot on the same PC:
https://apps.foldingathome.org/wu#project=18601&run=705&clone=4&gen=19 CPUid: A9B5945F22BB52B9
https://apps.foldingathome.org/wu#project=18448&run=6&clone=66&gen=269 CPUid: AAB5945F22BB52B9

See Issue #108 for other examples

**Comment by jcoffland** [comment]
I'm not sure this matters.  What is the reason for needing a separate ID?  In v8 it's more of a client ID than a CPU ID.

**Comment by Hou5e** [comment]
OK. I don't need separate CPUids, I was just reporting the inconsistency. It sounds like the web page should be updated to reflect that it's a Client Id now, (Remove the bottom line), here: https://apps.foldingathome.org/cpu

**Comment by jcoffland** [comment]
Removed.  Thanks.
