### ISSUE TITLE
Logging: Display upload / download file size in file transfer messages

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#113]
Mentioned on [Folding Forum](https://foldingforum.org/viewtopic.php?t=39073)
FAH v7 shows the data transfer size, and FAH v8 doesn't yet:

Example:
FAH v7: `08:58:08:WU00:FS00:Downloading 22.07MiB`
FAH v7: `11:01:16:WU00:FS00:Uploading 22.93MiB to 206.223.170.146`

FAH v8: `06:14:18:I1:/RG2:WU23:Downloading WU`
06:14:18:I1:OUT6:> POST https://fah1.innovatr.ca/api/assign HTTP/1.1
06:14:18:I3:Connecting to fah1.innovatr.ca:443
06:14:46:I1:OUT6:< fah1.innovatr.ca:443 HTTP/1.1 200 HTTP_OK
06:14:47:I1:/RG2:WU23:Received WU

FAH v8: `11:09:51:I1:/RG2:WU23:Uploading WU results`
11:09:51:I1:/RG2:WU23:Uploading WU results
11:09:53:I1:OUT13:> POST https://fah1.innovatr.ca/api/results HTTP/1.1
11:09:53:I3:Connecting to fah1.innovatr.ca:443
11:20:15:I1:OUT13:< fah1.innovatr.ca:443 HTTP/1.1 200 HTTP_OK
11:20:15:I1:/RG2:WU23:Credited

Similar to Issue #71

**Comment by jcoffland** [comment]
Size is now displayed in the progress updates.  These don't show yet on Windows/macOS.
