### ISSUE TITLE
Remove old init.d service in Linux pre install 

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#114]
Many people may not uninstall v7 before installing v8.

**Comment by marcosfrm** [comment]
Once `preinst` is back (#152):

```sh
#!/bin/sh -e

NAME=fah-client

case "$1" in
  install)
    # on initial install, try to remove leftover v7 init script
    systemctl kill FAHClient 2>/dev/null || true
    rm -f /etc/init.d/FAHClient
    ;;

  upgrade)
    systemctl stop $NAME || true
    # remove old, possibly outdated service symlink
    systemctl disable $NAME || true
    ;;
esac
```

v7's `postrm` (remove) calls `invoke-rc.d FAHClient stop` (forwarded to `systemctl stop FAHClient`) but the init script is so nasty it does not actually stop:

```
systemd[1]: Stopping FAHClient.service - LSB: Folding@home Client...
systemd[1]: FAHClient.service: Deactivated successfully.
systemd[1]: FAHClient.service: Unit process 675 (FAHClient) remains running after unit stopped.
systemd[1]: FAHClient.service: Unit process 681 (FAHClient) remains running after unit stopped.
systemd[1]: Stopped FAHClient.service - LSB: Folding@home Client.
```

We need to ask systemd to kill with SIGTERM the entire cgroup in advance.

**Comment by marcosfrm** [comment]
Hmm, we need to reload systemd after removing the init script. Let's only mess with this when the init script does exist.

```sh
  install)
    # on initial install, remove leftover v7 init script
    if [ -e /etc/init.d/FAHClient ]; then
      systemctl kill FAHClient || true
      rm -f /etc/init.d/FAHClient
      systemctl daemon-reload
    fi
    ;;
```

**Comment by kbernhagen** [comment]
I don’t think this is necessary now. 
The v8 deb has conflicts attributes now that should uninstall v7 automatically.

**Comment by kbernhagen** [comment]
But I have never tested it. Maybe it doesn’t remove init.d stuff.

**Comment by marcosfrm** [comment]
On v7 -> v8 upgrade, v7 is only removed, not purged. `/etc/init.d/FAHClient` is marked as "conffile" and only removed on purge (weird behaviour from Debian). In other words old init script will stay there and... running, because it is so broken that v7's `postrm` stop does not work.

Another option is only call `systemctl kill FAHClient || true` to stop it, then show a warning in `postinst` telling users to purge the old package, removing it from dpkg database. Something like this:

```sh
    echo
    echo "The Folding@home client is now installed"
    echo
    if [ -e /etc/init.d/FAHClient ]; then
      echo "You probably upgraded from the old v7 client."
      echo "It is recommended purge the old package to remove leftover files:"
      echo
      echo "  apt purge fahclient"
      echo
      echo "Note that previous configuration will also be removed."
      echo
    fi
    echo "File locations:"
    ...
```

Probably more sane.

**Comment by kbernhagen** [comment]
I do not want to encourage a purge, because that destroys the v7 config, which would normally be adopted.

**Comment by kbernhagen** [comment]
Normal expectation of user who have v7 is to simply upgrade.

**Comment by kbernhagen** [comment]
Purge also deletes any unfinished v7 work, which a user may want to finish by reinstalling v7. This works properly on macOS. Don't know about other platforms.

**Comment by kbernhagen** [comment]
Are you saying an explicit purge of v7 is needed for full removal of init.d scripts?

**Comment by kbernhagen** [comment]
Can the v8 purge successfully also do a v7 purge, or is it too late?

Sorry for my confusion.

**Comment by kbernhagen** [comment]
I suppose suggesting purge would be ok if the installer copied the v7 config instead of linking to it.

Is leaving `/etc/init.d/FAHClient` alone harmless once v7 is auto-removed?

**Comment by marcosfrm** [comment]
> Are you saying an explicit purge of v7 is needed for full removal of init.d scripts?

Yes.

> Can the v8 purge successfully also do a v7 purge, or is it too late?

Nope.

> Is leaving /etc/init.d/FAHClient alone harmless once v7 is auto-removed?

`/etc/init.d/FAHClient` can stay there because v7's `postrm` (remove) will call `update-rc.d -f FAHClient remove`, disabling it. v8 needs at least kill it otherwise the thing keeps running.

What about this?

`preinst`:

```sh
#!/bin/sh -e

NAME=fah-client

case "$1" in
  install)
    # old init script is broken and does not stop when told so
    if [ -e /etc/init.d/FAHClient ]; then
      systemctl kill FAHClient || true
    fi
    ;;

  upgrade)
    systemctl stop $NAME || true
    # remove old, possibly outdated service symlink
    systemctl disable $NAME || true
    ;;
esac
```

`postinst`:

```sh
    ...

    # migrate v7 configuration on initial install
    if [ -z "$2" ] && [ -e /etc/fahclient/config.xml ]; then
      mv /etc/fahclient/config.xml $CLIENT_HOME/
      chown $NAME:$NAME $CLIENT_HOME/config.xml
      echo
      echo "v7 client configuration migrated to $CLIENT_HOME/config.xml"
      echo
      echo "It is recommended purge the old package to remove leftover files:"
      echo
      echo "  apt purge fahclient"
      echo
    fi

    ...
```
(do not create symlink)

**Comment by kbernhagen** [comment]
Thanks. I added your last bit of code to my PR.

Also need to handle an existing config link in v8 home on upgrade.

On upgrade, if `%CLIENT_HOME/config.xml` is a link to `/etc/fahclient/config.xml`, replace link with moved config file.

What would be the most compatible linux sh code for that?

**Comment by marcosfrm** [comment]
> Also need to handle an existing config link in v8 home on upgrade.

On v8->v8 upgrades it will not migrate, because `$2` will be set. Note that v7->v8 is not considered upgrade by `dpkg` (`$2` not set) as the packages are different.

**Comment by kbernhagen** [comment]
Well, the old service is disabled instead of completely removed. User can purge the v7 package after installing v8.
