### ISSUE TITLE
Wrong project descriptions

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-client-bastet#116]
According to web control, I'm running (between 5 computers), the following (listed under "projects"):

18448 Cancer by Dylan Novack
18449 Cancer by Dylan Novack
18452 Cancer by Dylan Novack
18453 Cancer by Rafal Wiewiora
18717 Cancer by Rafal Wiewiora

Yet clicking the links in the "work units" section gives the page https://stats.foldingathome.org/project/[number] showing:

18448 Influenza by Dylan Novack
18449 Influenza by Dylan Novack
18452 Cancer by Dylan Novack
18453 Cancer by Dylan Novack
18717 Cancer by Rafal Wiewiora

So that's 40% correct, 20% with the wrong researcher, and 40% with the wrong subject.

**Comment by jcoffland** [comment]
Moved to https://github.com/FoldingAtHome/fah-web-client-bastet/issues/80
