### ISSUE TITLE
Show donor rank in web control

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-client-bastet#117]
Would it possible for those of us who are competitive, to put my rank at the top of the web control?  I'm currently going to https://stats.foldingathome.org/donor/name/PeterHucker_1HK9mWMp2xTK3f7fjowi1mCCbczu2EgFyR to view it.

**Comment by jcoffland** [comment]
This is a fah-web-client-bastet issue and is covered here: https://github.com/FoldingAtHome/fah-web-client-bastet/issues/88
