### ISSUE TITLE
Add support for command line state control

### ISSUE THREAD

**Issue by Josh65-2201** [FoldingAtHome/fah-client-bastet#119]
V7 has support for starting (--send-unpause), pausing (--send-pause) and finishing (--send-finish) via the command line for use in task scheduler. I can't find these for v8

**Comment by kbernhagen** [comment]
Until the client supports those commands, you might try my script:

[lufah - Little Utility for FAH v8](https://github.com/kbernhagen/lufah)

**Comment by marcosfrm** [comment]
These options are very useful for text only servers. Other possible candidates:

- Get/set configuration: `--send-command 'options cfg1=value1 cfg2=value2'` (`cfg1` to get, `cfg1!` to use default value).
- Queue information: `--send-command queue-info`.
- Dump WU. In v7: `--send-command 'slot-delete 00'` (or `01`, etc).

**Comment by jcoffland** [comment]
I wonder if a Python interface might be more useful than how this was implemented in v7.  A Python script/library could also be run in a continuous mode where it constantly monitored a client.  It could also login to your F@H account and give you access to all your machines.

The only downside I see is that Windows users would need to install Python but these days that's pretty easy.  Microsoft even offers it in their app store.

**Comment by kbernhagen** [comment]
My [lufah](https://github.com/kbernhagen/lufah) script is python, runs on all platforms, and is working well for me.

My python skills are admittedly weak. There is no chance of adding node support without a lot of help.

**Comment by kbernhagen** [comment]
I have not used it, but there is https://pyinstaller.org/

**Comment by kmb-abc** [comment]
Any progress on restoring the pause/unpause from previous client versions? I am not exactly thrilled to have my system cranking away during work hours. I loved being able to help by setting up scheduler to run in designated hours. May need to drop my participation if this cannot be restored in timely manner.

**Comment by kbernhagen** [comment]
As far as I know, the only scheduler for v7, besides roll-your-own, was the Chrome Folding in the dark plugin.

See also
https://github.com/FoldingAtHome/fah-web-client-bastet/issues/53

**Comment by kmb-abc** [comment]
Clearly I have not paid attention to my system's F@H efforts. I only recently realized it was not running, so I updated the client. Original setup had systemctl timer services set up as described here: https://www.ctrl.blog/entry/how-to-fahclient-schedule.html#section-linux
I would be nice to restore the command input options this solution was leveraging.

**Comment by kbernhagen** [comment]
You can use those systemd files now with v8 using my script.
If needed, install [pipx](https://pipx.pypa.io/).
As the user that will run the service units, pipx install [lufah](https://pypi.org/project/lufah/):
```sh
pipx install lufah
```

Modify the systemd files slightly:

`ExecStart=/usr/bin/FAHClient --send-pause`
Becomes
`ExecStart=%h/.local/bin/lufah. pause`

`ExecStart=/usr/bin/FAHClient --send-unpause`
Becomes
`ExecStart=%h/.local/bin/lufahfah . fold`

**Comment by kbernhagen** [comment]
Note that you will not make work unit deadlines if you restrict folding hours too much.

You might prefer to start folding early, then set finish a couple hours later.

**Comment by jcoffland** [comment]
v8.4.4 includes a Python script ``fahctl`` that can send ``fold``, ``pause`` and ``finish`` to the v8 client from the command line.  Use @kbernhagen's ``lufah`` for more control options.

**Comment by kbernhagen** [comment]
https://learn.microsoft.com/en-us/windows/win32/taskschd/about-the-task-scheduler

To use fahctl, you may need to open a powershell window and install dependencies. 

```
python -m pip install websocket-client

fahctl —help
```

**Comment by cad42s13** [comment]
I see in commit 6d889a4 that a script was added in a scripts directory.  But I don't see a scripts directory in C:\Program Files\FAHClient.

I feel this issue should be reopened as having to install python and use a third party scripts is more of a workaround than a fix.

There is a native command line interface which supports lots of settings.  I can turn "fold on idle" on / off from the native command line so should really be able to fold all, pause and finish.

I understand this will be a low priority given that a workaround exists, but think it should remain open.

**Comment by kbernhagen** [comment]
The v8.5.6 release on Windows will install `fahctl.py` and `fahctl.bat` next to the client.

All you should need is then python 3 and `pip install websocket-client` to use `fahctl`.
