### ISSUE TITLE
HiveOS integration

### ISSUE THREAD

**Issue by andrasfuchs** [FoldingAtHome/fah-client-bastet#12]
[HiveOS](https://hiveos.farm/) is one of the most popular tailor-made Linux operating systems for cryptocurrency mining rigs. These rigs have usually 6+ high-end GPUs in them. Although a typical rig operator is profit oriented, I think that they would give up a few percentage of their processing power to donate to FAH if they had the option.

For this to happen, FAH would need to be integrated as a miner. Technically this would mean to follow [HiveOS's miner integration brief](https://github.com/minershive/hiveos-linux/blob/master/hive/miners/MINERS.md).

**Comment by jcoffland** [comment]
We would welcome contribution of such an integration but this is currently outside of the scope of our project goals.
