### ISSUE TITLE
Exception: In thread 2: Failed to rename 'log.txt' to 'logs\log-20230221-001620.txt'

### ISSUE THREAD

**Issue by dmafackler** [FoldingAtHome/fah-client-bastet#120]
Windows 10 x64. 8.1.13.

Revised ProgramData\FAHclient\logs directory so that local Users have permission to write to the directory. Testing to make sure it was just target directory permissions.
[log-20230221-001620.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/10788932/log-20230221-001620.txt)

**Comment by kbernhagen** [comment]
I believe this exception usually means another client instance is already running and has log.txt open.

The permissions are already supposed to allow write for everyone.
If not, then that would be a bug in the Windows installer. (@Hou5e)

**Comment by Hou5e** [comment]
I started running FAH v8.1.13 on a Win10 PC again, and log rotate errors seem to happen (every time?) on Windows. Closing and restarting FAH properly moves and renames the log file from the root of the data folder to the 'logs' folder with no permissions errors (and there are likely no threads holding open the log file on FAH startup). It doesn't seem like a permissions problem. I can copy files, rename, or delete the logs in the folder without permissions errors.

When I was running this with the command line (or config.xml) option on a previous version with this Windows PC, I think it worked OK. This error seems more like a thread holding open the log file when the rotate needs to happen (doesn't seem to happen on Linux).

In this example, the 3rd log rotate happened during a WU download, and hung the client:
```
*********************** Log Rotated 2023-02-24T00:00:17Z ***********************
2023-02-24:00:00:17:E :Exception: In thread 7: Failed to rename 'log.txt' to 'logs\log-20230224-000017.txt': The process cannot access the file because it is being used by another process.
.
.
*********************** Log Rotated 2023-02-25T00:00:44Z ***********************
2023-02-25:00:00:44:E :Exception: In thread 19: Failed to rename 'log.txt' to 'logs\log-20230225-000044.txt': The process cannot access the file because it is being used by another process.
.
.
2023-02-25:23:58:02:I1:/RG1:WU49:Downloading WU
2023-02-25:23:58:02:I1:OUT565:> POST https://ds03.scs.illinois.edu/api/assign HTTP/1.1
2023-02-25:23:58:02:I3:Connecting to ds03.scs.illinois.edu:443
*********************** Log Rotated 2023-02-26T00:00:24Z ***********************
2023-02-26:00:00:24:E :CON565:Exception: Failed to rename 'log.txt' to 'logs\log-20230226-000024.txt': The process cannot access the file because it is being used by another process.
2023-02-26:00:13:23:I1:OUT563:< stxfahwork01.silicontx.com:443 HTTP/1.1 200 HTTP_OK
2023-02-26:00:13:23:I1:/RG1:WU48:Credited
```
When I closed and restarted the client, it was able to rotate the entire (3-4 days) log file to the logs folder:
[log-20230227-203200.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/10847259/log-20230227-203200.txt)

I've set my config.xml to a shorter rotate period for testing this: `  <log-rotate-period v='3600'/>`  (1 hour), or `fah-client --log-rotate-period=3600`. I'll try the debug version to see if there are better error messages. I don't think this is installer related.

**Comment by kbernhagen** [comment]
I haven't seen this on macOS either.

I'm not familiar with how cbang/log/Logger handles threading.
But I would expect any threading issue would affect Windows and macOS equally.

On Windows, there is a subthread that runs the Windows event loop. The main thread runs the libevent loop.

On linux, there is just the main tread libevent loop.

On macOS, the main thread runs a CFRunLoop, and a subthread runs libevent.

**Comment by Hou5e** [comment]
The debug log has a few extra messages: [log-20230228-111938.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/10849637/log-20230228-111938.txt)
```
07:59:22:I1:/RG1:WU59:Completed 1550000 out of 5000000 steps (31%)
*********************** Log Rotated 2023-02-28T08:00:50Z ***********************
08:00:50:E :Exception: In thread 2: Failed to rename 'log.txt' to 'logs\log-20230228-080050.txt': The process cannot access the file because it is being used by another process.
08:00:50:E :
08:00:50:E :       At: src\cbang\os\SystemUtilities.cpp:716:rename()
08:00:50:E :Caught at: src\cbang\os\Thread.cpp:247:starter()
*********************** Log Rotated 2023-02-28T09:43:21Z ***********************
09:43:21:E :Exception: Failed to rename 'log.txt' to 'logs\log-20230228-094321.txt': The process cannot access the file because it is being used by another process.
09:43:21:E :
09:43:21:E :       At: src\cbang\os\SystemUtilities.cpp:716:rename()
09:43:21:E :Caught at: src\cbang\event\Event.cpp:165:call()
```
The logging stopped until the next WU started, in this example.
