### ISSUE TITLE
Linux installer: add groups video, render to client user

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#121]
Try to add client user to groups video and render for easier GPU folding.

Try for both regular and upgrade installs.

Users will still need to have appropriate gpu drivers installed.

**Comment by jcoffland** [comment]
The client runs as the user ``fah-client``.

**Comment by kbernhagen** [comment]
Yes, and to access a GPU it needs to also belong to groups video and/or render. Tis is mentioned on many threads on foldingforum. Probably also on discord and slack.

**Comment by jcoffland** [comment]
Done
