### ISSUE TITLE
Log app info after log rotation

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#122]
The rotated, new logs do not contain the app info.
This should always be at the top of log because it is needed for tech support.

**Comment by kbernhagen** [comment]
This might be easier if cbang [Logger](https://github.com/CauldronDevelopmentLLC/cbang/blob/master/src/cbang/log/Logger.cpp) `startLogFile()` had an optional callback.

**Comment by jcoffland** [comment]
The client now caches the last 100k lines so this is less of a problem.  Also, I think this could be better solved by https://github.com/FoldingAtHome/fah-web-client-bastet/issues/151.
