### ISSUE TITLE
Credits folder becomes large over time.

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#124]
The 'credits' folder grows over time, and could use periodic cleanup.
Linux example, 1.5 months of running FAHv8 (1896 credit files, ~26MB):
![image](https://user-images.githubusercontent.com/20870053/221864554-b8a642d2-fe02-4411-b08d-f4c361910a23.png)
The 'credits' folder could use a periodic cleanup at startup, or over 1000 files.

**Comment by jcoffland** [comment]
See #59.
