### ISSUE TITLE
Disable system sleep when a work unit is running

### ISSUE THREAD

**Issue by Josh65-2201** [FoldingAtHome/fah-client-bastet#125]
I have my system set to sleep when not used but F@A to go over night. Issue is the system will go into sleep when it running so the WU makes no progress.

**Comment by kbernhagen** [comment]
@jcoffland If you choose to use the disable sleep code, it needs to exposed in Web Control. Some people don’t want it.

I should remind you that it needs to be toggled in exactly one thread on Windows.

**Comment by jcoffland** [comment]
NOTE: The v7 client prevents the system from sleeping if it's not on battery.

**Comment by informatorius** [comment]
It should still be possible for user to send system to sleep manually

**Comment by jcoffland** [comment]
Complete in v8.3.2.
