### ISSUE TITLE
GPUs mixed up

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-client-bastet#126]
I installed Folding on a computer with a 4 core Intel CPU which has built in Intel HD graphics, and an AMD discrete GPU.  I wished to run Folding on the AMD GPU.  When I ticked this and only this in the web control, I find only the Intel HD graphics runs a task (obvious by looking at the % usage and temperatures in MSI Afterburner).  I then tried ticking the Intel HD box thinking they were mixed up, but that one gives the error:

15:49:51:E ::WU13:HTTP_SERVICE_UNAVAILABLE: {"error":"No appropriate assignment"}
15:49:51:I1::WU13:Retry #7 in 2 mins 8 secs

**Comment by hucker75** [comment]
19:39:08:I1::WU43:  opencl-device 2 specified
19:39:20:I1::WU43:WARNING:Console control signal 1 on PID 4172
19:39:20:I1::WU43:Exiting, please wait. . .
19:39:23:I1:OUT14:< vav19.fah.temple.edu:443 HTTP/1.1 200 HTTP_OK
19:39:24:I1::WU44:Received WU
19:39:25:I3::WU43:Dumping NWAt8YSJTROdhR80olH18g0iP6flLCTYa2KXcBxpnq4
19:39:26:I1::WU43:ERROR:102: Core startup was interrupted by client.
19:39:26:I1::WU43:Folding@home Core Shutdown: INTERRUPTED
19:39:26:I3::WU44:Dumping XPQ10vJRdVeasZ5zyat00wi5YoLeYgG6zfHXtNEl_nI
19:39:26:I1::WU44:Sending dump report
19:39:26:I1:OUT15:> POST https://vav19.fah.temple.edu/api/results HTTP/1.1
19:39:26:I3:Connecting to vav19.fah.temple.edu:443
19:39:27:I1:OUT15:< vav19.fah.temple.edu:443 HTTP/1.1 200 HTTP_OK
19:39:27:I1::WU44:Dumped
19:39:27:I1::WU43:Core returned INTERRUPTED (102)
19:39:27:I1::WU43:Sending dump report

**Comment by kbernhagen** [comment]
According to OP, this is with v8.1.13 on latest Windows 11.

The problem still exists with v8.1.14.

https://foldingforum.org/viewtopic.php?p=359418#p359418

**Comment by hucker75** [comment]
Unless someone else can reproduce this, I'd be tempted to assume it's my dodgy computer.  As I said over on the forum, it's a second hand mining MB with BIOS problems.  It may be reporting the connected GPUs oddly.  Boinc is fine with it, Folding isn't.

**Comment by hucker75** [comment]
If I click dump on the CPU task which is "waiting", it starts getting work for the GPUs again, but for how long?

**Comment by hucker75** [comment]
So I changed the settings to use all CPU cores, and when it tries to request work I get:

13:05:08:E ::WU25:Exception: Could not get IP address for vav22.fah.temple.edu: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.

**Comment by jcoffland** [comment]
These are two different problems.  Please try not to hijack other issues, it get confusing from our end.

Second issue moved to: https://github.com/FoldingAtHome/fah-client-bastet/issues/128

**Comment by hucker75** [comment]
My apologies, it looked like part of the same problem.

**Comment by jcoffland** [comment]
No problem.  For some reason, I first thought you were a second reporter hijacking the original issue.

**Comment by jcoffland** [comment]
I am attempting to sort out some issues with GPU detection.  v8.1.14 introduces a lot of changes to this code.

**Comment by jcoffland** [comment]
This should be fixed in v8.1.15 which is now available.  Please reopen this issue if it's not fixed.
