### ISSUE TITLE
CPU work units not restarting on error

### ISSUE THREAD

**Issue by jon-ault** [FoldingAtHome/fah-client-bastet#127]
I discovered yesterday that one of my folding machines has been having problems with CPU work units for at least a couple months now, going back to when it was still running v7. Under v7 when a CPU work unit hit an exception it would restart from the last checkpoint; the work units might restart a couple times but they would eventually complete. Under v8, as soon as a CPU work unit has a problem it dumps & downloads a new one, it doesn't appear to be trying to restart from the last checkpoint. As a result, most CPU work units on this machine are getting dumped under v8.

I don't know if this is intentional behavior for the beta (because you want to see all the errors) but if it is not then I think the v7 approach was better.

**Comment by jcoffland** [comment]
It depends a lot on the type of error.  Some errors are non-recoverable.  I would need to see the log files to tell the difference.

**Comment by jon-ault** [comment]
Here's a log file that covers the last 10-11 days of February. Most of the errors are "Core returned UNKNOWN_ENUM (3221225477)".

There's a couple occurrences of "Core returned UNKNOWN_ENUM (3221225501)".

There's an occurrence of "Core returned UNKNOWN_ENUM (3221226505)" following an Exception access violation error.

There's an occurrence of:
20:15:34:I1::WU548:Watchdog triggered, requesting soft shutdown down
20:15:34:I1::WU548:Folding@home Core Shutdown: WU_STALLED
20:15:35:W ::WU548:Core returned WU_STALLED (127)

[log-20230228-192008.txt.zip](https://github.com/FoldingAtHome/fah-client-bastet/files/10889884/log-20230228-192008.txt.zip)

**Comment by jon-ault** [comment]
And here's one with 

04:35:24:I1::WU736:ERROR:FFT plan mismatch - bad plan or direction.
04:36:03:W ::WU736:Core returned UNKNOWN_ENUM (2147483651)

[log-20230302-064315.zip](https://github.com/FoldingAtHome/fah-client-bastet/files/10890449/log-20230302-064315.zip)

**Comment by jon-ault** [comment]
For comparison, here's a similar UNKNOWN_ENUM error under v7 at the end of January where it just restarts:

15:12:49:WARNING:WU01:FS00:FahCore returned an unknown error code which probably indicates that it crashed
15:12:49:WARNING:WU01:FS00:FahCore returned: UNKNOWN_ENUM (-1073741819 = 0xc0000005)
15:12:49:WU01:FS00:Starting
15:12:49:WU01:FS00:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" C:\ProgramData\FAHClient\cores/cores.foldingathome.org/win/64bit-avx2-256/a8-0.0.12/Core_a8.fah/FahCore_a8.exe -dir 01 -suffix 01 -version 706 -lifeline 20108 -checkpoint 15 -np 6
15:12:49:WU01:FS00:Started FahCore on PID 18364
15:12:49:WU01:FS00:Core PID:18752
15:12:49:WU01:FS00:FahCore 0xa8 started

**Comment by jon-ault** [comment]
I looked at all the remaining v8 logs & didn't find any additional error types beyond the ones noted above. It's mostly UNKNOWN_ENUM (3221225477) and occasionally UNKNOWN_ENUM (3221225501).

**Comment by jcoffland** [comment]
The core is crashing for some reason.  So the client is doing the right thing in this case.  There's no reason to retry the WU in this case.  It seems to always crash on core 0xa8 projects.

**Comment by jon-ault** [comment]
> The core is crashing for some reason. So the client is doing the right thing in this case. There's no reason to retry the WU in this case. It seems to always crash on core 0xa8 projects.

OK, but here's a log from the last half of January where v7 was seeing the same error code (0xC0000005) and it just kept restarting until it finished. Was v7 doing the wrong thing?

[log-20230129-013700.zip](https://github.com/FoldingAtHome/fah-client-bastet/files/10890523/log-20230129-013700.zip)

**Comment by jcoffland** [comment]
v8.1.16 which is out, should work like v7 in this respect.
