### ISSUE TITLE
More GPUs than CPU cores causes severe miscalculation

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-client-bastet#129]
Running 8.1.15.

I have 6 GPUs connected to a 4 core computer (the CPU is easily fast enough to support this, as it's fairly fast and the GPUs are fairly old).

Looks like it's seen a negative number of free CPUs and gone nuts.  I also can't see the slider to adjust it.  I end up with a 64 core task which slows the machine down severely.

Can you please sort this, and let me know if there's a workaround for just now?  Could I edit a config file somewhere?

![resource](https://user-images.githubusercontent.com/66015018/223283202-dd0ac8a2-c7c4-4e0c-b717-ba52dcc9d0b5.jpg)

![large number](https://user-images.githubusercontent.com/66015018/223283216-d212a673-38c5-402d-9c2e-049cfd6082dc.jpg)

![64](https://user-images.githubusercontent.com/66015018/223283224-30e6dea0-307d-44a1-883d-9a11bb559acc.jpg)

**Comment by jcoffland** [comment]
Should be fixed in v8.1.16.
