### ISSUE TITLE
Add ability to take one GPU out of action (with immediate effect)

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-client-bastet#135]
I run Boinc aswell, and sometimes would like to switch a GPU out of use for Folding.  For example, I had received a World Community Grid Boinc task (they're rare on GPU) and was trying to switch off the GPU which was trying to do both at once.  I disabled a GPU (1 of 5 GPUs), and nothing happened, they all kept running, but in [issue 115](https://github.com/FoldingAtHome/fah-client-bastet/issues/115) you told me that would pause the work unit.  Although I wasn't trying to pause the task, I wanted it to continue on another GPU when another task finished.  I assume when that particular GPU finished the task, it would stop, but I wanted it immediate, mainly so I could tell I had the right GPU!

**Comment by jcoffland** [comment]
Yes, it should stop immediately but you have to save the settings by clicking the "Save" button.

**Comment by hucker75** [comment]
It doesn't stop.  I unticked a GPU as shown, then clicked save.  They all kept running, both in the web viewer and by watching GPU usage in MSI Afterburner.

![image](https://user-images.githubusercontent.com/66015018/231733346-dc1b0f9b-3a1a-446b-8b69-07c8c8ab14be.png)

**Comment by jcoffland** [comment]
Does this work correctly with v8.1.17?

**Comment by hucker75** [comment]
I hadn't realised there was a new version out.  I installed it, but the problem persists.

I did notice when I upgraded one of the machines (the one I view them from), it warned me the others were out of date.  Is that a new feature?  And will it work if it's own client is out of date?

**Comment by jcoffland** [comment]
All machines need to be updated for the fix to work.

**Comment by hucker75** [comment]
What I meant in the second paragraph was, in future, when the next version is released, if none of the machines have the new version, will I be informed in the version column?  Or does one machine have to have been updated so it spots the difference?

**Comment by jcoffland** [comment]
No updates needed to see the version difference between the latest.
