### ISSUE TITLE
"Fold when idle" option should be made clearer

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-client-bastet#140]
Currently there is an option "fold when idle".  My first thought whenever I see that is "yes, I want it to fold when idle".  Actually, I want it to always fold.  It should read "fold ONLY when idle".  I think I'm ticking it to allow it more access to the computer, when actually I'm restricting it.

**Comment by jcoffland** [comment]
This is a front-end issue so it should be in fah-web-client-bastet.  I've changed the text and it will be in the next release.  Thanks!
