### ISSUE TITLE
Folding dies after folding successfully starts

### ISSUE THREAD

**Issue by TessellateDataScience** [FoldingAtHome/fah-client-bastet#142]
I've noticed my F@h system unexpectedly dies and stops folding after I have configured and started it. I believe this is caused by my internet being interrupted (goes offline for some time), leading to my OS's internet manager software (firmware?) to cease seeing my router. 

I'm wondering has this been seen before? Or would you be interested in a email notification (etc) to at least let people know it's happened? 

Next time I'll see if I can get more from my F@h error log. My system is currently dedicated to F@h, running Ubuntu with 4 x GPUs.

**Comment by jcoffland** [comment]
I have not seen this behavior.  By "dies" do you mean the software exits or just that folding does no longer proceeds?  We need more information in order to have an idea of what's going on here.  Please reopen the issue when you have log files to post.

**Comment by TessellateDataScience** [comment]
My definition of dies is that folding no longer proceeds AND each GPU-related process is killed, but the system physically appears normal (lights & fans are running), misleading me to believe it was folding even tho it wasn't. I'll have to wait until it happens again (around ~2 weeks).

**Comment by TessellateDataScience** [comment]
**Log file (tail) after 'dying' event:** 

22:55:37:I1::WU2861:Completed 2500000 out of 2500000 steps (100%)
22:55:37:I1::WU2861:Average performance: 104.727 ns/day
22:55:38:I1::WU2861:Checkpoint completed at step 2500000
22:55:42:I1::WU2861:Saving result file ../logfile_01.txt
22:55:42:I1::WU2861:Saving result file checkpointIntegrator.xml
22:55:42:I1::WU2861:Saving result file checkpointState.xml.bz2
22:55:42:I1::WU2861:Saving result file positions.xtc
22:55:42:I1::WU2861:Saving result file science.log
22:55:42:I1::WU2861:Saving result file xtcAtoms.csv.bz2
22:55:42:I1::WU2861:Folding@home Core Shutdown: FINISHED_UNIT
22:55:43:I1::WU2861:Core returned FINISHED_UNIT (100)
22:55:43:I1::WU2861:Uploading WU results
22:55:43:I1:OUT1249:> POST https://highland1.seas.upenn.edu/api/results HTTP/1.1
22:55:43:I3:Connecting to highland1.seas.upenn.edu:443
22:55:45:I1::WU2861:UPLOAD 2% 230.81KiB of 12.90MiB
22:55:46:I1::WU2861:UPLOAD 29% 3.72MiB of 12.90MiB
22:55:47:I1::WU2861:UPLOAD 57% 7.39MiB of 12.90MiB
22:55:48:I1::WU2861:UPLOAD 78% 10.09MiB of 12.90MiB
22:55:50:I1::WU2861:UPLOAD 100% 12.89MiB of 12.90MiB
22:55:51:I1:OUT1249:< highland1.seas.upenn.edu:443 HTTP/1.1 200 HTTP_OK
22:55:51:I1::WU2861:Credited
22:55:52:I1::Added new work unit: cpus:0 gpus:gpu:04:00:00,gpu:05:00:00,gpu:06:00:00
22:55:52:I1::WU2868:Requesting WU assignment for user nchowlett team 1063658
22:55:52:I1:OUT1250:> POST https://assign1.foldingathome.org/api/assign HTTP/1.1
22:55:52:I3:Connecting to assign1.foldingathome.org:443
22:55:53:I1:OUT1250:< assign1.foldingathome.org:443 HTTP/1.1 200 HTTP_OK
22:55:53:I1::WU2868:Received WU assignment 7wLq49VIXKa_J5uu47vK-ZE2TSA3TVmMyzvwrE0FHwk
22:55:53:I1::WU2868:Downloading WU
22:55:53:I1:OUT1251:> POST https://highland1.seas.upenn.edu/api/assign HTTP/1.1
22:55:53:I3:Connecting to highland1.seas.upenn.edu:443
22:55:55:I1::WU2868:DOWNLOAD 100% 46B of 46B
22:55:55:I1:OUT1251:< highland1.seas.upenn.edu:443 HTTP/1.1 503 HTTP_SERVICE_UNAVAILABLE
22:55:55:E ::WU2868:HTTP_SERVICE_UNAVAILABLE: {"error":{"message":"Please wait","code":503}}
22:55:55:I1::WU2868:Retry #1 in 2 secs
22:55:57:I1::WU2868:Requesting WU assignment for user nchowlett team 1063658
22:55:57:I1:OUT1252:> POST https://assign2.foldingathome.org/api/assign HTTP/1.1
22:55:57:I3:Connecting to assign2.foldingathome.org:443
22:55:59:I1:OUT1252:< assign2.foldingathome.org:443 HTTP/1.1 200 HTTP_OK
22:55:59:I1::WU2868:Received WU assignment vI1v7sY4QkxhpNREUOfb_dJtbnu5v_83beXnp89oaqo
22:55:59:I1::WU2868:Downloading WU
22:55:59:I1:OUT1253:> POST https://vav19.fah.temple.edu/api/assign HTTP/1.1
22:55:59:I3:Connecting to vav19.fah.temple.edu:443
22:56:01:I1::WU2868:DOWNLOAD 7% 79.53KiB of 1.05MiB
22:56:02:I1::WU2868:DOWNLOAD 90% 962.33KiB of 1.05MiB
22:56:02:I1:OUT1253:< vav19.fah.temple.edu:443 HTTP/1.1 200 HTTP_OK
22:56:02:I1::WU2868:Received WU
22:56:45:I1::WU2862:Completed 2150000 out of 2500000 steps (86%)
22:56:46:I1::WU2862:Checkpoint completed at step 2150000
22:58:13:I1::WU2862:Completed 2175000 out of 2500000 steps (87%)
22:59:41:I1::WU2862:Completed 2200000 out of 2500000 steps (88%)
22:59:42:I1::WU2862:Checkpoint completed at step 2200000
23:01:10:I1::WU2862:Completed 2225000 out of 2500000 steps (89%)
23:02:37:I1::WU2862:Completed 2250000 out of 2500000 steps (90%)
23:02:38:I1::WU2862:Checkpoint completed at step 2250000
23:04:05:I1::WU2862:Completed 2275000 out of 2500000 steps (91%)
23:05:33:I1::WU2862:Completed 2300000 out of 2500000 steps (92%)
23:05:34:I1::WU2862:Checkpoint completed at step 2300000
23:07:01:I1::WU2862:Completed 2325000 out of 2500000 steps (93%)
23:08:29:I1::WU2862:Completed 2350000 out of 2500000 steps (94%)
23:08:29:I1::WU2862:Checkpoint completed at step 2350000
23:09:57:I1::WU2862:Completed 2375000 out of 2500000 steps (95%)
23:11:25:I1::WU2862:Completed 2400000 out of 2500000 steps (96%)
23:11:26:I1::WU2862:Checkpoint completed at step 2400000
23:12:53:I1::WU2862:Completed 2425000 out of 2500000 steps (97%)
23:14:21:I1::WU2862:Completed 2450000 out of 2500000 steps (98%)
23:14:21:I1::WU2862:Checkpoint completed at step 2450000
23:15:49:I1::WU2862:Completed 2475000 out of 2500000 steps (99%)
23:17:17:I1::WU2862:Completed 2500000 out of 2500000 steps (100%)
23:17:17:I1::WU2862:Average performance: 49.0909 ns/day
23:17:17:I1::WU2862:Checkpoint completed at step 2500000
23:17:19:I1::WU2862:Saving result file ../logfile_01.txt
23:17:19:I1::WU2862:Saving result file checkpointIntegrator.xml
23:17:19:I1::WU2862:Saving result file checkpointState.xml
23:17:20:I1::WU2862:Saving result file positions.xtc
23:17:20:I1::WU2862:Saving result file science.log
23:17:20:I1::WU2862:Saving result file xtcAtoms.csv.bz2
23:17:20:I1::WU2862:Folding@home Core Shutdown: FINISHED_UNIT
23:17:20:I1::WU2862:Core returned FINISHED_UNIT (100)
23:17:21:I1::WU2862:Uploading WU results
23:17:21:I1:OUT1254:> POST https://vav19.fah.temple.edu/api/results HTTP/1.1
23:17:21:I3:Connecting to vav19.fah.temple.edu:443
23:17:24:I1::WU2862:UPLOAD 10% 3.96MiB of 39.24MiB
23:17:25:I1::WU2862:UPLOAD 23% 8.87MiB of 39.24MiB
23:17:26:I1::WU2862:UPLOAD 41% 16.03MiB of 39.24MiB
23:17:27:I1::WU2862:UPLOAD 58% 22.97MiB of 39.24MiB
23:17:28:I1::WU2862:UPLOAD 76% 29.65MiB of 39.24MiB
23:17:30:I1::WU2862:UPLOAD 94% 37.09MiB of 39.24MiB
23:17:34:I1:OUT1254:< vav19.fah.temple.edu:443 HTTP/1.1 200 HTTP_OK
23:17:34:I1::WU2862:Credited
23:17:34:I1::Added new work unit: cpus:0 gpus:gpu:03:00:00,gpu:04:00:00,gpu:05:00:00,gpu:06:00:00
23:17:34:I1::WU2869:Requesting WU assignment for user nchowlett team 1063658
23:17:34:I1:OUT1255:> POST https://assign3.foldingathome.org/api/assign HTTP/1.1
23:17:34:I3:Connecting to assign3.foldingathome.org:443
23:17:36:I1:OUT1255:< assign3.foldingathome.org:443 HTTP/1.1 200 HTTP_OK
23:17:36:I1::WU2869:Received WU assignment 8jo-qAuaT2gY_VOJSx-CUBRKUO-m-ec_CrOpbsstOFA
23:17:36:I1::WU2869:Downloading WU
23:17:36:I1:OUT1256:> POST https://vav19.fah.temple.edu/api/assign HTTP/1.1
23:17:36:I3:Connecting to vav19.fah.temple.edu:443
23:17:38:I1::WU2869:DOWNLOAD 4% 79.53KiB of 1.81MiB
23:17:39:I1::WU2869:DOWNLOAD 66% 1.19MiB of 1.81MiB
23:17:39:I1:OUT1256:< vav19.fah.temple.edu:443 HTTP/1.1 200 HTTP_OK
23:17:39:I1::WU2869:Received WU

**Comment by TessellateDataScience** [comment]
Most recent dying event was caused by F@h attempting to allocate WU's to my CPU (disobeying my settings), and finding the resource not available.
