### ISSUE TITLE
GPU-Only Folding, runs CPU WU and downloads many extra CPU WUs

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#144]
Continuing from: https://foldingforum.org/viewtopic.php?t=39369

It looks like the AS might be making bad assignments for FAH v8 (Win10 or Linux, and not happening on FAH v7), CPU assignments for GPU folding. The CPU WUs all seem to be from: https://vav19.fah.temple.edu   (that can issue both: 0x22, 0xa8 project types. It doesn't seem like the certificate issue at the bottom of #141)

![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/71f36122-04ab-4da6-81f7-8219d0e62e44)
For GPU-Only Folding (this almost needs it's own setting), I personally don't want a (1)CPU-thread CPU WU trying to run because they typically take over 24 hours to run, where I would want like 8 threads to run that CPU WU (if I wanted to do CPU folding). For the v8 philosophy of letting FAH use the resources you allocate, this error is kind-of "by design". But, not what I personally want the PC to do since it will only be running during business hours each day. I also personally don't want 4 CPU WU's to download for each Resource Group, and sit on the PC for days, when it can't get a GPU WU.

[50 minutes later] After another WU completed, it picked up a few more CPU WUs:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/45fdc6a9-ddb2-4d96-8884-172e75386ff4)

[20 minutes later] Ending up with a pile of CPU-only folding (for GPU-only folding):
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/7082ff54-9efa-4f8d-abb4-e01171cfec9d)

[20 minutes later] After the WUs upload, then it got one GPU WU and continued one CPU WU (since it had 4 CPU WUs for that RG):
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/c74fd789-3af8-4b89-ac9f-9090597f94b1)

Debug version logs with passkey set to *****:
[log-20230902-12-3.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/12504991/log-20230902-12-3.txt) (log for the first screenshot image above)
[log-20230902-12-3-Later.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/12505122/log-20230902-12-3-Later.txt) (log for the last screenshot image)
[log-20230902-12-2.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/12504970/log-20230902-12-2.txt)
[log-20230902-12-1.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/12504971/log-20230902-12-1.txt)
Let me know if you need any additional info. Thanks!  😃

**Comment by TessellateDataScience** [comment]
I'm getting this too (disobeying my Settings to disable CPU-related folding), leading to ramping-down of folding on my parallelised GPU system. I'm running client v8.1.18. Shout out if you folks need anything more!

**Comment by jcoffland** [comment]
I've altered the AS configuration to hopefully fix this.  Please report back.  Thanks.

**Comment by Hou5e** [comment]
It seems like the issue is still occurring.
I only tested this once so far on a Win10 PC, and it got a CPU WU first and then a GPU WU about 20 seconds later.
[log-20230904-1-Win10.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/12512643/log-20230904-1-Win10.txt)

**Comment by jcoffland** [comment]
I'm working on a new version of the client which has many changes.  One of them is that it will allow you to enable GPUs but configure 0 CPUs.  We are moving away from automatically allocating one CPU for each GPU WU.

**Comment by jcoffland** [comment]
I think the problem now is that the client reserves one CPU for each GPU but the AS says it's not using that reserved CPU so the client requests a one CPU WU and gets it.  The zero CPU assignment problem described above should be fixed.

**Comment by Hou5e** [comment]
OK, thanks for the update.
So, ideally with the current client, we should set CPU=0 in the settings for GPU folding, which you can do with v8.1.18.
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/1a82db55-2428-42b7-80fd-e0e2ae933dcf)
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/ceaf3974-3d4e-42e6-9183-dfdc745e0d87)
It does work to fix the issue on the PCs I've tried it on.

**Comment by kbernhagen** [comment]
So, instead of allocating a cpu per gpu, will the client reduce the available_cpus per gpu?

**Comment by jcoffland** [comment]
@kbernhagen No, that would essentially be the same thing.  We're just assuming, possibly wrongly, that the CPU usage is negligible.  The user is free to make a correction by allocating less CPUs.

**Comment by TessellateDataScience** [comment]
> I've altered the AS configuration to hopefully fix this. Please report back. Thanks.

All my systems are go (no CPU allocation attempted)! Thanks Joseph.

**Comment by jcoffland** [comment]
fixed
