### ISSUE TITLE
After unlocking machine, Windows 10 fails to render.

### ISSUE THREAD

**Issue by cameronlyman** [FoldingAtHome/fah-client-bastet#145]
Occasionally, when I leave my machine locked to do folding and return many hours later, I find that Windows no longer renders properly. Folding continues to run, but Windows rendering is out of whack. This is an intermittent issue. Sometimes it returns to normal after waiting a long time with the screen unlocked.

Below you can see a screenshot of my two monitors. Notice that the taskbar at the bottom of the screen does not render.

![folding-at-home-bug](https://github.com/FoldingAtHome/fah-client-bastet/assets/20762251/1bc8c8b2-de7f-44cd-b819-431bd86d6e4f)

**Comment by jcoffland** [comment]
The Windows taskbar is outside of the control of Folding@home.  There must be a bug in your Windows OS.  It's possible that the bug is triggered by the extra load F@H puts on the system but there's nothing we can do about that.
