### ISSUE TITLE
Use KillMode=mixed in fah-client.service

### ISSUE THREAD

**Issue by marcosfrm** [FoldingAtHome/fah-client-bastet#146]
The default `KillMode=control-group` sends SIGTERM to *all* processes in service's control group. Can `fah-client` children handle that? In most cases when there is a main process doing children management like `fah-client`, `KillMode=mixed` is a better option. Only the main process (`fah-client`) gets SIGTERM while the final SIGKILL for all service's control group is still enforced if stop goes wrong (afer `TimeoutStopSec=`, by default 90s).

See:
https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=
https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutStopSec=

`KillMode=mixed` is supported since systemd 209, a pretty old version nowadays: CentOS 7 has 219, Debian 8 had 215.

**Comment by jcoffland** [comment]
The child processes (cores) can handle the ``SIGTERM`` but I agree, ``KillMode=mixed`` is probably better.

**Comment by marcosfrm** [comment]
Thanks: https://github.com/FoldingAtHome/fah-client-bastet/commit/757be08fcf1e60635f3cf183ac8fafc8fa1644b0.
