### ISSUE TITLE
Debian package installs fah-client.service at non-conformant path

### ISSUE THREAD

**Issue by marcosfrm** [FoldingAtHome/fah-client-bastet#148]
It is installed in `/usr/share/fah-client/`, with a symlink `/etc/systemd/system/fah-client.service -> /usr/share/fah-client/fah-client.service`.

This is confusing and problematic. If we disable it, the symlink is gone:

```
# systemctl disable fah-client.service
Removed "/etc/systemd/system/multi-user.target.wants/fah-client.service".
Removed "/etc/systemd/system/fah-client.service".
```

Enable will fail then...

```
# systemctl enable fah-client.service
Failed to enable unit: Unit file fah-client.service does not exist.
```

...since `/usr/share/fah-client/` is not part of systemd unit file load path:

https://manpages.debian.org/bookworm/systemd/systemd.unit.5.en.html#UNIT_FILE_LOAD_PATH

`fah-client.service` should be in `/lib/systemd/system/` (Debian does not use `/usr/lib/` yet).

**Comment by jcoffland** [comment]
Done.

**Comment by marcosfrm** [comment]
https://github.com/FoldingAtHome/fah-client-bastet/blob/093691e74ed87522acba49b522ce94c869ade747/install/debian/postinst.in#L26-L27

`systemctl daemon-reload` is necessary before these two, otherwise systemd will not "see" the unit file.

**Comment by jcoffland** [comment]
Done
