### ISSUE TITLE
Was /etc/fah-client directory ever used?

### ISSUE THREAD

**Issue by marcosfrm** [FoldingAtHome/fah-client-bastet#154]
https://github.com/FoldingAtHome/fah-client-bastet/blob/a414147855b7e89fb9a4ca7211b99239b67b158f/install/debian/postrm#L12

Debian v8 package's purge try to remove `/etc/fah-client` directory. I could not find any reference to it.

**Comment by kbernhagen** [comment]
I don’t think it was ever used.
Could be wrong.

**Comment by kbernhagen** [comment]
We will be using `/etc/fah-client` now.
This issue can be closed.
