### ISSUE TITLE
DEB/RPM: only enable/start on first install?

### ISSUE THREAD

**Issue by marcosfrm** [FoldingAtHome/fah-client-bastet#160]
Every time both packages are installed and upgraded they enable and start themselves automatically. I understand this behaviour on first install to help less tech-savvy users. For upgrades, they should not do that.

If you agree, I can open a PR changing it.

**Comment by marcosfrm** [comment]
Hmm, DEB is complicated because we always disable in `preinst` on upgrades. This was the motivation for

https://github.com/FoldingAtHome/fah-client-bastet/pull/150/commits/36a29ebb42cfd1c503a40afb152a1b5192e900dc
https://github.com/FoldingAtHome/fah-client-bastet/pull/151/commits/b6bdd149afd34870c082dc18db571af8604e030a

In RPM there is no such complication since the macros do not touch enablement state and rely on `systemctl try-restart` on upgrades.

RPM's behaviour can be implemented in DEB too, but that crazy symlink created by older v8 packages poiting to `/usr/share` may be a problem.

**Comment by kbernhagen** [comment]
I think enable and start is appropriate for both install and upgrade.

If you can determine the previous states on upgrade, being in those states would be reasonable.

I think almost nobody will have stopped or disabled the service.
Remember that a running service can have folding paused.

**Comment by kbernhagen** [comment]
Maybe do a disable only if the old service symlink exists?
Then re-enable if we explicitly disabled?

**Comment by marcosfrm** [comment]
> I think enable and start is appropriate for both install and upgrade.

I disagree.

> If you can determine the previous states on upgrade, being in those states would be reasonable.

Easy: do not enable or disable and call `try-restart` in the upgrade path. systemd RPM macros do exactly that.

This works for DEB:

`postinst.in`:
```sh
systemctl daemon-reload || true

# only enable/start on initial install
if [ -z "$2" ]; then
  systemctl -q enable $NAME || true
  systemctl start $NAME || true
else
  # upgrade
  # reenable if fixing broken symlink
  if dpkg --compare-versions $2 lt 8.2.1; then
    systemctl -q enable $NAME || true
  fi

  systemctl try-restart $NAME || true
fi
```

`preinst`:
```sh
  upgrade)
    # remove broken symlink created by old v8 packages
    if dpkg --compare-versions $2 lt 8.2.1; then
      systemctl -q disable $NAME || true
    fi
```

Version 8.2.1+ has `fah-client.service` in the proper place.

What do you think?

**Comment by kbernhagen** [comment]
I’m not sure 8.2.1 is ok.

**Comment by marcosfrm** [comment]
It is. I tested.

**Comment by kbernhagen** [comment]
Was it only the 8.1 series, or was it fixed in 8.2.1 ?

**Comment by marcosfrm** [comment]
It was fixed in 8.2.1.

**Comment by kbernhagen** [comment]
Doesn’t deb preinst need changes?

**Comment by marcosfrm** [comment]
Yes. I posted above...

**Comment by kbernhagen** [comment]
Ok.

**Comment by kbernhagen** [comment]
Could you make the PR, please?
