### ISSUE TITLE
v8.2.4 on Win10 fails to get WU

### ISSUE THREAD

**Issue by rhavern** [FoldingAtHome/fah-client-bastet#168]
15:30:28:I3:Connecting to assign1.foldingathome.org:443
15:30:28:I1:OUT2:> POST https://assign1.foldingathome.org/api/assign HTTP/1.1
15:30:29:I1:OUT2:< HTTP/1.1 503 HTTP_SERVICE_UNAVAILABLE
15:30:29:E :OUT2:HTTP_SERVICE_UNAVAILABLE: {"error":"No appropriate assignment"}

See attached full log.
[20230130 v8.2.4 failure to engage.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/13207151/20230130.v8.2.4.failure.to.engage.txt)

**Comment by jcoffland** [comment]
Looking at the server logs it appears you have the project key set to 11111 which does not exist.
