### ISSUE TITLE
GPU WU running on CPU, apparently.  Core 23 newly in use

### ISSUE THREAD

**Issue by dillitante** [FoldingAtHome/fah-client-bastet#169]
before23 starts before the wu that caused the new core to download, shows the download and install.

after noticing the cpu usage and stopping the client, 23-log shows the restart.

[before23.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/13210149/before23.txt)
[23-log.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/13210156/23-log.txt)

**Comment by jcoffland** [comment]
Both logs show that the core is using the GPU.  Is the problem that core 0x23 is also using CPU?  That's to be expected.

Notice both logs have these lines:

    12:34:29:I1::WU73:  Using OpenCL on OpenCL platformId 2 and gpu 0
    12:34:29:I1::WU73:  GPU info: Platform: OpenCL: Clover
    12:34:29:I1::WU73:  GPU info: PlatformIndex: 0
    12:34:29:I1::WU73:  GPU info: Device: AMD Radeon VII (vega20, LLVM 15.0.7, DRM 3.54, 6.2.0-34-generic)

So it is using the GPU.  It may also use some CPU especially as it is starting up.

**Comment by jcoffland** [comment]
Seems related to #176

**Comment by jcoffland** [comment]
Reopen this if you can provide more info.
