### ISSUE TITLE
GPUs white list not downloading

### ISSUE THREAD

**Issue by ZexMaxwell001** [FoldingAtHome/fah-client-bastet#172]
running freshly installed windows 10
Running drivers from this website: https://www.nv-drivers.eu/download-P106090-drivers-for-Windows10-64bit.html
Windows knows what the video cards are and sees them working: https://imgur.com/Bk6DN97
But FAH shows this: https://imgur.com/lFb0uyK
I was going to use this fix posted here: https://foldingforum.org/viewtopic.php?p=327123#p327123
but the folder is not found in beta.
Video cards works. they ran out of the box with Linux.

Device: NVIDIA P106-090
Subvender: Zotac/PC Partner
DID: 10DE 1C09 - 19DA 6438

Logs: https://pastebin.com/kKbHjWri
its saying it failed to get the info. But when I looked at the webpage on the machine, its able to load the page. I even turned off the firewall on the machine it it still wasn't able to get it. firewall on the router is untouched from when it was able to get the info for linux.

come to think of it. its not even allowing the CPU to fold.

https://foldingforum.org/viewtopic.php?p=362756#p362756

**Comment by jcoffland** [comment]
You client is failing to download the list of supported GPUs from F@H.  This could indicate that the client is not reaching the network at all.  Is it being blocked by Windows firewall?  That GPU is supported.

**Comment by ZexMaxwell001** [comment]
ok. revisited this issue after 3 weeks and only 2 things changed.
windows finally activated with my microsoft account. 
installed Malwarebytes to manage my firewall settings. 
is MS blocking FAH? who knows and I dont really have the time to reinstalled windows 10 on bare metal to figure it out. >.<

**Comment by jcoffland** [comment]
Reopen this if you have more info.
