### ISSUE TITLE
17 day estimated time to completion

### ISSUE THREAD

**Issue by dillitante** [FoldingAtHome/fah-client-bastet#176]
claims to be running on a GPU.  It is not.

![cropped Screenshot from 2023-11-29 23-27-29](https://github.com/FoldingAtHome/fah-client-bastet/assets/149438412/b93e7069-b097-4919-be79-b346a329398d)
[using 23 on cpu.txt.gz](https://github.com/FoldingAtHome/fah-client-bastet/files/13508644/using.23.on.cpu.txt.gz)

**Comment by jcoffland** [comment]
Can you post the log?

**Comment by dillitante** [comment]
yes, certainly.

one thing that seems odd to me is the ????  where I would expect to see 47:00:00

18:33:35:I1::WU216:  GPU info: DeviceIndex: 0
18:33:35:I1::WU216:  GPU info: Vendor: 0x1002
18:33:35:I1::WU216:  GPU info: PCI: ??:??:??

I have captured the logs and work files and ...  from around this time, if more info would be useful

[wu216.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/13513913/wu216.txt)

**Comment by jcoffland** [comment]
Please reopen this if you have more info.
