### ISSUE TITLE
On Windows with Firefox, the overall start 'Fold'ing button doesn't start Folding

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#185]
Win10-FAH v8.3.0 (Debug), Builder file 113 from 2023-12-30.
In Windows, pressing the overall start 'Fold'ing button doesn't start Folding (It works on Linux). The RG control works though.

{Edited} --> On Windows, it doesn't issue anything for the overall start 'Fold'ing button, just show log to view nothing:
`08:59:46:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T08:59:46.666Z"}`

On Linux, it issues this, shown in the log:
`[92m12:33:16:D3:msg: {"state": "fold", "cmd": "state", "time": "2023-12-30T12:33:16.467Z"}[0m`

The last few lines were from pressing the Start Folding RG control:
```
08:59:46:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T08:59:46.666Z"}
09:02:19:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T09:02:19.124Z"}
09:02:40:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T09:02:40.816Z"}
09:03:09:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T09:03:09.047Z"}
09:04:00:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T09:04:00.223Z"}
09:04:20:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T09:04:20.876Z"}
09:04:38:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T09:04:38.374Z"}
09:04:49:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T09:04:49.916Z"}
09:04:55:D3:msg: {"state": "fold", "group": "", "cmd": "state", "time": "2023-12-30T09:04:55.785Z"}
09:04:55:D1:Default:Remaining CPUs: 0, Remaining GPUs: 1, Active WUs: 0
09:04:55:I1:Default:Added new work unit: cpus:0 gpus:gpu:04:00:00
09:04:55:D3:Default:Unit enabled
09:04:55:D1:Default:Remaining CPUs: 0, Remaining GPUs: 0, Active WUs: 1
```
Same with a RG starting the next WU:
```
10:47:47:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T10:47:34.228Z"}
10:47:47:D3:msg: {"state": "pause", "group": "/RG1", "cmd": "state", "time": "2023-12-30T10:47:43.027Z"}
10:47:47:I1:Loaded cores/openmm-core-23/windows-10-64bit/release/fahcore-23-windows-10-64bit-release-8.0.3/FahCore_23.exe
10:48:10:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T10:48:10.089Z"}
10:49:11:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T10:49:11.584Z"}
10:49:29:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T10:49:29.751Z"}
10:50:11:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T10:50:11.727Z"}
10:50:31:D3:msg: {"state": "fold", "group": "/RG1", "cmd": "state", "time": "2023-12-30T10:50:31.178Z"} 
```

**Comment by jcoffland** [comment]
Note that ``08:59:46:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T08:59:46.666Z"}`` is just web control enabling the log.  It will happen every time you open log view and has nothing to do with pause/fold.

I suspect there is an error in the browser console when you click ``Fold`` on Windows.

**Comment by Hou5e** [comment]
Yes, you're right, I pressed the show log button after pressing the main Fold button many times, only to not have any entries in the log for starting folding. I was logged-in and using a Firefox browser.

I'm guessing: this issue, #186, and #187, are related to the last 2 sentences in this post: https://github.com/FoldingAtHome/fah-client-bastet/issues/178#issuecomment-1858568404 about the web socket not reporting status.

Testing this again with the latest Windows (Debug) builder file 16, I get the same behavior:
If logged out, then Pause/Resume works correctly locally.
When logged-in, then you get nothing pressing either the main Fold or Pause buttons, locally or remote.

**Comment by jcoffland** [comment]
I just tested this in Windows with Firefox, Chrome and Edge.  All three worked as expected.  Is this still a problem?

**Comment by Hou5e** [comment]
Yes, it still happens for me (with the latest Windows Release build 57 or Debug build 117). The requirements to make this happen are: Use Firefox (use a private window to avoid cache issues) on Windows, Login to your FAH account. I get this now about the certificate, and I press OK:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/250e5751-8fbc-4115-b827-d00f273507d1)

Press the Fold or Pause buttons. I get no responses. It also doesn't connect to the remotes.
In this screenshot, the same Windows PC is the 2 left browsers, and Linux is on the right. I'm pressing the fold button many times and it's not doing anything. 
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/176c2d38-d905-463f-883b-84d8d53bffba)

It sounds like the setup of 'SubjectAltName' in the certificate is a common issue about self-signed certificates. Are either of these links related or useful about this problem?
https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate/57511038#57511038
https://serverfault.com/questions/1115557/generate-self-signed-certificate-for-firefox-to-accept

**Comment by jcoffland** [comment]
The certificate problem should be fixed now.  Does it also resolve this issue?

**Comment by Hou5e** [comment]
This is working now.
