### ISSUE TITLE
On Windows with Firefox, FAH isn't displaying the remote PC's status

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#187]
Possibly related to #188

On Windows, Win10-FAH v8.3.0 (Debug), Builder file 114 from 2023-12-30, Firefox browser:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/abb860b1-e825-49e0-9393-9cd9c5518777)

On Linux, Mint21.1 (Ubuntu 22.04)-FAH v8.3.0 (Debug), Builder file 14 from 2023-12-30, Firefox browser:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/0cd5e206-a963-48c0-b329-4715e71814f9)

**Comment by jcoffland** [comment]
This is also working fine for me.  Is it still an issue?

I've got Firefox 121.0.

**Comment by Hou5e** [comment]
Yes, it still happens for me with the latest build. I've got Firefox 121.0, as well (on both PCs below). My other screenshots today of logged-in regular window and private browsing window are in #185 & #186, too.

Adding a Win10 Laptop for another point of reference was similar:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/e81304f3-06b2-410b-92c9-0041dcbff832)
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/408e7438-c534-49b8-91af-41a20f812acb)

Note: the Win10-PC machine didn't pickup the new laptop after it was added (none of the other PCs displayed it either, like the laptop isn't connected to the FAH server):
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/82d791cc-19d7-438b-94c6-fe937667e05f)
It's like some things are being blocked or ignored by node1.foldingathome.org, or it's really not connecting for some types of network traffic??
Let me know if you think making a different account token, or making a different account would help. Or if network router settings might be blocking something (I didn't see any red flags when I looked today).

**Comment by jcoffland** [comment]
Do you have any log files from the non-connecting clients?

**Comment by jcoffland** [comment]
I thought we mixed the ``MS-organization-access`` certificate issue?  The node should not be requesting certificates any more.  Perhaps there's a browser caching issue going on here.

**Comment by Hou5e** [comment]
The 'accept a certificate' issue #188 was (and still is) happening with all the browsers I used in the last day or so (even Firefox, now).
Using a Private Browsing window avoids any cache issues.
The laptop was a first-time install of FAH, so there were no cache issues for that one.

Win10-PC Log file: [log-20240104-002337.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/13829840/log-20240104-002337.txt)
Win10-Laptop Log file: [Win10-Laptop_log-20240104-090823.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/13829889/Win10-Laptop_log-20240104-090823.txt)
(Note: the web socket messages didn't start for the first ~9 hours on the laptop's first WU ever)

The laptop did finally show up in the lists of PCs on the other computer's Remotes reviewing, It just took a while.

**Comment by jcoffland** [comment]
I think I found the certificate problem.  I've made another change to the node software.  Does Windows still present the cert dialog now?

**Comment by Hou5e** [comment]
On Windows, yes, you still get a certificate dialog (just login with a Private or Incognito window).
If you pick OK, then remote don't work (Chrome re-prompts you constantly. Firefox has a checkbox to 'Remember this decision').
Chrome:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/279d7a05-3f97-40df-9e15-b85a48a9287f)
Firefox:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/a8a8da92-5669-4176-8298-cc7e510e01ae)

If you pick {cancel | Don't send a certificate}, then it works in Chrome or Firefox.
Firefox:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/37ed84f3-b2e6-4d0f-ada8-f3418d14f1fe)

**Comment by jcoffland** [comment]
I've made another attempt to fix the client certificate issue.  Please test again.

**Comment by Hou5e** [comment]
That make the certificate dialog disappear, but the remotes don't show. There should be 2 remotes online in this image:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/c5da530e-671f-4b16-935c-8067f53369b4)

**Comment by jcoffland** [comment]
The remotes must not be connected.  When the node restarts it seems to some times take a long time for the clients to reconnect.  I think we've made progress though if you're no longer seeing the cert dialog.

**Comment by Hou5e** [comment]
Yep, you're right. I just restarted the FAH Clients to force the update and now it looks like it's working.

**Comment by jcoffland** [comment]
I think the reconnect issue is fixed in the latest client build.

**Comment by Hou5e** [comment]
This looks good. The remotes show up.
