### ISSUE TITLE
`short_description` purpose

### ISSUE THREAD

**Issue by marcosfrm** [FoldingAtHome/fah-client-bastet#192]
Are not `summary` and `description` enough? `short_description` only has one less paragraph:

https://github.com/FoldingAtHome/fah-client-bastet/blob/969812344a041a004b6dbf56b5dd3a26a08a476a/SConstruct#L81-L84

Which is incorrectly formatted in `description`:

```
Folding@home performs research on human diseases using the computing
resources of volunteers.
Folding@home client software which downloads and runs Folding@home simulation work units.

Finished work units are returned to the Folding@home servers for points.

Fold on your own or in a team.  Compete with folders around the world to earn the most points while contributing to science.

Monitor and control the client via your browser.

**Comment by kbernhagen** [comment]
I may have created it. 
Look at packager and friends. 

I know short_description is favored for the osx pkg component description.

If it’s only used for osx, you can eliminate it.

**Comment by kbernhagen** [comment]
I only find `short_description ` in `cbang/config/flatdistpkg`

I think you can eliminate it.

**Comment by kbernhagen** [comment]
I am removing `short_description` from `cbang/config/flatdistpkg`.

**Comment by kbernhagen** [comment]
`short_description` is vestigial, completely unused, can be eliminated

**Comment by kbernhagen** [comment]
NO. Leave that alone.

**Comment by kbernhagen** [comment]
Well, if the text doesn’t match, you might update it. 
it is used for localization of strings in the macOS installer pkg.
