### ISSUE TITLE
Update: 2023 --> 2024

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#193]
Updates for the new year: 2023 --> 2024
Like in the Windows Sys-Tray app, for the 'About':
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/69701abb-9d39-47eb-9fc1-44a0cf290168)

**Comment by kbernhagen** [comment]
That’s probably in SConstruct. Maybe package.json

**Comment by kbernhagen** [comment]
WinOSImp::showAbout()

**Comment by kbernhagen** [comment]
Isn’t the copyright ultimately available from BuildInfo, same as version?

**Comment by jcoffland** [comment]
Done
