### ISSUE TITLE
CPU setting don't work correctly with v8.3 if browser cache is not refreshed

### ISSUE THREAD

**Issue by Adanorm** [FoldingAtHome/fah-client-bastet#194]
Hello,

I upgraded a VM Ubuntu 22.04 Desktop from FAH8.2.4 to FAH8.3.1
It fold, OK.

When I go on my setting via app.foldingathome.org, my CPUs settings are lost everytime I try to set it (to 8 in this sample).
![2024-01-08_095524](https://github.com/FoldingAtHome/fah-client-bastet/assets/46302945/357203c6-50da-4894-98ea-9c9b366439ff)

Same issue when I use alpha.fordingathome.org :
![2024-01-08_095606](https://github.com/FoldingAtHome/fah-client-bastet/assets/46302945/035c9315-0997-4385-8536-06214aec5127)

**Comment by jcoffland** [comment]
Strange.  First off, app.foldingathome.org and v8.3.x are not currently compatible.  You must use the alpha web control with the alpha client.  However, it's odd that you don't see the selected number of CPUs in either view.

Are there any errors in your browser console? Use F12 to open the console.

Can you post the client log file?

**Comment by Adanorm** [comment]
Is it possible that I have a weird frankenclient mixed between 8.2.x and 8.3 ? No migration of 8.2 to 8.3 on the .deb ?

**Comment by kbernhagen** [comment]
You MUST use https://alpha.foldingathome.org

Config cpus is stored in the groups in v8.3.

**Comment by kbernhagen** [comment]
v8.2 did not have resource groups, but the `peers` settings from v8.1 might have remained as cruft.


v8.3 sees that and creates groups, but you might see things like GPUs enabled in more than one group.

**Comment by kbernhagen** [comment]
None of the images you posted were of the latest Web Control.
You might need to force refresh the browser page.

**Comment by Adanorm** [comment]
![2024-01-08_114920](https://github.com/FoldingAtHome/fah-client-bastet/assets/46302945/f0ef022b-4f96-4d3d-ae70-f89fac07961f)

You were right

**Comment by kbernhagen** [comment]
Ah, the joys of alpha testing...

**Comment by jcoffland** [comment]
This is very useful feedback.  It looks like we should do two things:

1. Warn that the Web Control on app.foldingathome.org is out of date when the client is v8.3.x and point to the correct front-end.
2. Trigger an automatic refresh of Web Control in the browser when it is updated on the server.

**Comment by jcoffland** [comment]
This should be fixed.  Web Control now forces a refresh when it detects a newer client.
