### ISSUE TITLE
Sleep not inhibited after restart on Linux

### ISSUE THREAD

**Issue by marcosfrm** [FoldingAtHome/fah-client-bastet#200]
After service restart, if the client starts with a WU already in active state, the inhibitor is not set (missing from `systemd-inhibit --list` output). After a pause/start cycle however it is set again.

I could not find anything obvious in the log.

```
fah-client[2314]: 09:47:11:D3:msg: {
fah-client[2314]: 09:47:11:D3:  "config": {
fah-client[2314]: 09:47:11:D3:    "user": "Anonymous",
fah-client[2314]: 09:47:11:D3:    "team": 0,
fah-client[2314]: 09:47:11:D3:    "passkey": "",
fah-client[2314]: 09:47:11:D3:    "cause": "any",
fah-client[2314]: 09:47:11:D3:    "groups": {
fah-client[2314]: 09:47:11:D3:      "": {
fah-client[2314]: 09:47:11:D3:        "on_idle": false,
fah-client[2314]: 09:47:11:D3:        "cpus": 1,
fah-client[2314]: 09:47:11:D3:        "gpus": {},
fah-client[2314]: 09:47:11:D3:        "beta": false,
fah-client[2314]: 09:47:11:D3:        "key": 0
fah-client[2314]: 09:47:11:D3:      }
fah-client[2314]: 09:47:11:D3:    }
fah-client[2314]: 09:47:11:D3:  },
fah-client[2314]: 09:47:11:D3:  "cmd": "config",
fah-client[2314]: 09:47:11:D3:  "time": "2024-01-15T09:47:11.180Z"
fah-client[2314]: 09:47:11:D3:}
```

Should `keep_awake` be here? Just a guess...

**Comment by jcoffland** [comment]
Are you sure you've got the right versions of Web Control and fah-client?  You should see ``keep_awake`` in the config with the latest builds.

Note, I haven't release the latest Web Control to https://alpha.foldingathome.org/ yet so you would need to run your own.

**Comment by jcoffland** [comment]
I went ahead and pushed the latest Web Control to  https://alpha.foldingathome.org/.  You should be able to control ``keep_awake`` and ``on_battery`` now.

**Comment by jcoffland** [comment]
I pushed a commit to cbang that should fix this issue.

**Comment by marcosfrm** [comment]
Thanks. Fixed.
