### ISSUE TITLE
Support HTTP proxy

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-bastet#206]

**Comment by Jersh** [comment]
Any sing of proxy support being in the pipeline, or at least support for using the widnows defined proxy details?

**Comment by jcoffland** [comment]
This feature is not in high demand.

**Comment by kbernhagen** [comment]
Someone on Linux reporting DNS problems with proxy:
 https://foldingforum.org/viewtopic.php?t=41682

**Comment by jcoffland** [comment]
The next client alpha will have basic HTTP proxy support.  SOCKS, pac, wpad and HTTPS proxies will not supported at least initially.

I'm not sure how common [SOCKS](https://en.wikipedia.org/wiki/SOCKS) is anymore.  It's a completely different protocol.  I believe really only SOCKS5 is used.

[pac](https://en.wikipedia.org/wiki/Proxy_auto-config) and [wpad](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol) are used for proxy auto-configuration.  Evaluating pac requires running JavaScript.  I wonder if the OS does pac and/or wpad on it's own.  It would make more sense for the OS to do the auto discovery and use it to configure the manual proxy settings.  It seems silly for every app on the system to have to know these protocols.

I'm also not sure how common HTTPS proxies are.  They require two layers of SSL encryption to connect to https websites.  HTTP proxies have an address like ``http://127.0.0.1:3128`` whereas HTTPS proxies have an address like ``https://127.0.0.1:3128``.  Double encryption is more complicated to implement but could be added if there's sufficient demand.

**Comment by kbernhagen** [comment]
I think auto proxy configuration is handled by higher level platform specific apis.

**Comment by jcoffland** [comment]
Completed as described above in v8.4.0 alpha.
