### ISSUE TITLE
Periodic log rotation doesn't create new file

### ISSUE THREAD

**Issue by dymil** [FoldingAtHome/fah-client-bastet#209]
basically what https://foldingforum.org/viewtopic.php?t=39416 reported last year. I see
> *********************** Log Rotated 2024-02-05T00:00:15Z ***********************

at the bottom of log.txt (or in web control), but any new logging is just dropped on the floor until I quit and restart the client.

Yesterday I have one log ending
> 23:57:34:I1::WU11:Completed 312500 out of 1250000 steps (25%)
> *********************** Log Rotated 2024-02-04T00:00:03Z ***********************

and then the next log, hours later (presumably when I noticed and restarted) begins with WU12.

This is on Windows 10, for what it's worth. Nothing exotic about the directories involved, i.e., C:\ProgramData\FAHClient.

I poked around a bit in the cbang logging code to try to understand, but it seems like all roads lead to [Logger::createStream](https://github.com/CauldronDevelopmentLLC/cbang/blob/ce14aab9846ad9c1f78b425254958a28edc80b4e/src/cbang/log/Logger.cpp#L422), where the periodic rotation happens. I haven't tried building cbang myself to test, but I could imagine a Windows issue which manifests in [`startLogFile`](https://github.com/CauldronDevelopmentLLC/cbang/blob/ce14aab9846ad9c1f78b425254958a28edc80b4e/src/cbang/log/Logger.cpp#L171), since I don't see any tests for the logging.

**Comment by kbernhagen** [comment]
Which client version?

**Comment by dymil** [comment]
Release, just the download from https://foldingathome.org/beta/

**Comment by kbernhagen** [comment]
Please consider trying v8.3.1 alpha 
https://foldingathome.org/alpha/

**Comment by jcoffland** [comment]
This should already be fixed in v8.3.2.

**Comment by dymil** [comment]
D'oh, I didn't know about the alpha or look at the releases/commits on GitHub, such as cac9a08073e2ea6017ce1b26f2f80e940b3b8c62. I'll see with v8.3.1 now, as I can't run v8.3.2 after a separate issue #210 arose.

**Comment by dymil** [comment]
Seems fixed indeed!
