### ISSUE TITLE
Use secure websockets

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#21]
Maybe this is already planned?

Besides the security benefits, Safari refuses to connect with no way to allow:

    [Log] Opening a websocket at url:ws://127.0.0.1:7396/api/websocket (index.74396761.js, line 1)
    [Warning] [blocked] The page at https://app.foldingathome.org/ was not allowed to run insecure content from ws://127.0.0.1:7396/api/websocket. (index.74396761.js, line 1)

Chrome silently allows the localhost websocket, even with insecure content set to blocked in preferences. But not all Mac users have Chrome.

Also, Chrome seems to be using 3x the cpu time as Safari on my M1 Mac mini with the frontend app.

**Comment by kbernhagen** [comment]
Is a self-signed certificate possible?
Safari may allow that.
If not, such a cert could be marked as trusted by the user in Keychain Access.

**Comment by jcoffland** [comment]
The client would need to generate a CA and keys, self-sign and then get the CA into the local store.  Is an app allowed to do this?  It could work.

**Comment by kbernhagen** [comment]
No, I think user action is required to trust a cert used by the system/web browser.
It's probably a bad idea to train users to manually trust certs.

Chrome does have an experimental flag to allow self-signed localhost certs, without actually trusting them. The user would have to enable this.

**Comment by kbernhagen** [comment]
There is an open bug ticket and very long discussion here:

https://bugs.webkit.org/show_bug.cgi?id=171934

My understanding is that the WebKit team iu strongly opposed to allowing more localhost access from random, public, ad-injected web pages. They don't care what the w3c spec says.

Some developers apparently have their daemon installer create and install a self-signed root CA for 127.0.0.1, NOT "localhost".

I think it's easier to just have the frontend detect Safari/WebKit and a blocked WebSocket, and put up a friendly message to try another browser for this site.

**Comment by jcoffland** [comment]
I think the thing to do is generate a CA in the client, install that CA's certificate in the OS root cert store.  Then generate a certificate from the CA for the web interface.

 * On Linux copy the CA cert to ``/etc/ssl/certs/``
 * On Windows run this command: ``certutil.exe -addstore root <certificate>``
 * On macOS this is supposed work: ``sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <certificate>``
 
It's unclear to me if these methods affect the browsers certificate stores as well.  We will need to test them.

**Comment by jcoffland** [comment]
This is not practical.  There's no way to create a valid cert and now we have F@H accounts and F@H node.
