### ISSUE TITLE
8.3.2 fails to start due to missing ``Revision`` key?

### ISSUE THREAD

**Issue by dymil** [FoldingAtHome/fah-client-bastet#210]
Relevant log lines below:

> 12:59:07:I1:Opening Database
12:59:07:E :Exception: Info category 'Folding@home Client' does have key 'Revision'.

Perhaps a consequence of 7ae353bc9fa083b872d0a2a0b4c1383693986bdd

Windows 10, upgraded from 8.3.1 without clearing data.

**Comment by jcoffland** [comment]
This was caused by cbang not correctly detecting the ``git`` executable on Windows and therefor not setting ``Revision`` in the info block.  v8.3.3 fixes this.

**Comment by kbernhagen** [comment]
@dymil You may be interested in Alpha and Dev [discussions](https://github.com/FoldingAtHome/fah-client-bastet/discussions)
