### ISSUE TITLE
DNS lookup always fails if network was not up when client launched

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#223]
DNS lookup always fails if network was not up when client is launched.

Tested on macOS 13.6.4 intel, fah v8.3.6 dev debug.

- turn off wifi
- launch client on command line
- wait for a DNS error to be logged
- turn wifi on
- DNS errors continue

**Comment by jcoffland** [comment]
Can you provide a log file?  There are two different ways C! does DNS lookups.  I'd like to figure out which one is causing this problem.

**Comment by jcoffland** [comment]
Is the error message: ``Could not get IP address for ...``?

**Comment by kbernhagen** [comment]
I'm not seeing `Could not get IP address for`

Except:
```
[msg] Nameserver 127.0.0.1:53 has failed: request timed out.
[msg] All nameservers have failed
04:25:53:W :Connection:CON1:DNS lookup failed for node1.foldingathome.org:443
04:25:53:I1:Account:Account websocket closed: NONE msg=Connection failed
```

[log.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/14391747/log.txt)

**Comment by jcoffland** [comment]
I think I found the problem.  libevent's DNS implementation stops using a DNS server once it has failed.  When all DNS servers have failed it can no longer resolve names.  So either the implementation needs to be fixed or we need a new async DNS implementation.  I see two reasonable options:

1. Periodically check the DNS server state and restart/readd the DNS servers when they have failed.
2. Try using the OS's async DNS interface.  Could be very different on Windows, Linux and macOS.

**Comment by jcoffland** [comment]
I may have fixed it.  DNSBase was using the libevent option ``EVDNS_BASE_DISABLE_WHEN_INACTIVE``.  I believe this was disabling the DNS server reconnect logic.

**Comment by kbernhagen** [comment]
Not fixed.

**Comment by jcoffland** [comment]
How long did you wait for the network to recover?  The current logic first waits 10s before probing if the DNS server is backup.  If that fails, it multiples the timeout by 3.  So it's then 30s, 90s, 270s, etc.  And it can go all the way up to 1hr.

If you let the client sit for awhile after the network is back up, and you have the libevent debug messages on, you should eventually see: ``Nameserver 127.0.0.1:53 is back up``.

**Comment by kbernhagen** [comment]
I will try again. I only waited a minute.

**Comment by kbernhagen** [comment]
How do I turn on the libevent debug logging?

**Comment by jcoffland** [comment]
It looks like you have it on.  ``[msg] Nameserver 127.0.0.1:53 has failed: request timed out.`` is from libevent.

**Comment by kbernhagen** [comment]
No recovery in over an hour with wifi restored after about 30s.
[log-20240224-235931.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/14394839/log-20240224-235931.txt)

Here's a 6 min run with `--debug-libevent=true`:
[Terminal Saved Output.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/14394833/Terminal.Saved.Output.txt)

**Comment by jcoffland** [comment]
Ok.  Looks like I need to dig deeper into the libevent DNS client implementation.

**Comment by jcoffland** [comment]
This should be fixed in v8.3.6 but I haven't tested it yet on Windows or macOS

**Comment by Hou5e** [comment]
This seems related, but slightly different.
FAH v8.3.7 (from alpha release page) on Windows, where a WU upload had many repeated error messages:
```
DNS lookup failed for ... 
Failed response: CONNECT
.
.
Writer closed with open DICT
std::exception: bad allocation
```
Then FAH eventually crashed.
[log-20240403-034529.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/14846554/log-20240403-034529.txt)

**Comment by jcoffland** [comment]
fixed
