### ISSUE TITLE
Some clients disconnect from node at 0:00 UTC

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-bastet#224]
It's unclear why this happens.  It's unlikely to be an issue with fah-node because fah-node does not think the clients are disconnected until after they timeout.  It's possible fah-client is at fault but it could also be caused by ISPs or some other hop on the network dropping connections briefly at 0:00 UTC.  Further investigation is need.

See #189 for some context.

**Comment by Hou5e** [comment]
This was an odd error with FAH v8.3.7 (from alpha release page) on Windows. Not Folding, just viewing remotes, at 0UTC the DNS lookup and websocket connection messages wouldn't stop:
Before the log rotation at 0UTC: [log-20240328-000045.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/14846460/log-20240328-000045.txt)
After the log rotation at 0UTC: [log-20240328-235413.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/14846462/log-20240328-235413.txt)
This error might be related to issue #223

**Comment by wvm4** [comment]
Don't know if this helps, but I'm still experiencing this issue on v8.3.14
Only seemed to happen on my ubuntu devices though, for some reason my windows device I was using while the others got disconnected stayed connected.

**Comment by jcoffland** [comment]
This should be fixed with the latest node upgrade.
