### ISSUE TITLE
Infinite WU processing loop: Exception: Key 'wu' not found

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#231]
Ideally, preventing this situation would be ideal.

At least (4) PCs processed the same WU over 20-60 times in a row in the past 2-3 days with FAH v8.3.8.
When it finished, there was a JSON processing error, so it retries computing the entire WU again, over, and over, and over...

`Exception: Key 'wu' not found`
`Exception: At JSON path: wu`

Project: 18220 (Run 11942, Clone 1, Gen 15)
Project: 12297 (Run 11, Clone 33, Gen 107)
[log-20240504-215439.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15211088/log-20240504-215439.txt)

Project: 17642 (Run 0, Clone 47, Gen 99)
[log-20240504-225159.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15211181/log-20240504-225159.txt)

Project: 14969 (Run 0, Clone 39, Gen 27)

Project: 18220 (Run 855, Clone 1, Gen 16)
Project: 18221 (Run 16063, Clone 0, Gen 12)

**Comment by Hou5e** [comment]
It looks like this is fixed with FAH v8.3.9.

[log-20240507-000035.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15228349/log-20240507-000035.txt)
In the log file on Linux, **WU11097** looks like it had the 'wu' error with v8.3.8, and was upgrade installed to v8.3.9, where it retried and completed the WU and moved on to the next WU (so that was good). There was one new error message at the end of submitting the WU results:
`23:33:21:I1:OUT7:< HTTP/1.1 406 HTTP_NOT_ACCEPTABLE`
`23:33:21:E :OUT7:HTTP_NOT_ACCEPTABLE: {"error":{"message":"Quit","code":406}}`

Project: 12454 (Run 11, Clone 2, Gen 121)
https://apps.foldingathome.org/wu?project=12454&run=11&clone=2&gen=121#project=12454&run=11&clone=2&gen=121
Not credited for the submission (yet), and it looks like it failed for someone else. But, that's probably the right outcome for an error.

**Comment by jcoffland** [comment]
Yes, that was the intended behavior.  I'm confused as to how the WU ended up not having a "wu" record in it's data.  That maybe another bug.  Please let me know if it happens again.  Regardless, getting stuck in a loop is worse.
