### ISSUE TITLE
FAH Crash on Windows

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#235]
FAH v8.3.10 Debug version on Windows crashed 10 minutes before the 0 UTC log rotation...

[log.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15270298/log.txt)

The FAH system tray program closed after this message:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/d63bfbbe-bfdb-4bdb-8dc5-affa6b7a5fec)

![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/bf724c95-1007-4d00-8f38-55598604da38)

Restarting FAH, it's recomputing WU1642 (the one that finished and was uploading or about to upload).
WU1642 finished the second time and was credited. That WU failed for someone else before: https://apps.foldingathome.org/wu?project=12458&run=10&clone=7&gen=183#project=12458&run=10&clone=7&gen=183

**Comment by Hou5e** [comment]
This issue happened again with FAH v8.3.13 Debug on Windows (30 minutes after the log rotation, with pretty much the same project=12457, and was 12458 the last time):
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/ba84ae08-8162-4b09-8030-81f3f33aa7d2)
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/fc57a316-d258-4702-b396-f63f060d660c)

Before log rotation: [log-20240516-000000.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15328214/log-20240516-000000.txt)
Error happened at the end of this log: [log-20240516-003443.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15328220/log-20240516-003443.txt)

**Comment by jcoffland** [comment]
I'm have trouble reproducing this.  Could you capture a stack trace?  You need to have Microsoft Visual Studio installed.  The Community version is free.

When you get the crash pop up, don't close it.  Open MSVS.  You don't need to create a project.  Click "Continue without code".  Then select the ``Debug`` menu, ``Attach to process`` and select the ``FAHClient.exe`` process and click ``Attach``.  Then go back to the error dialog and click ``Retry``.  After a few seconds you should see stack trace in MSVS on the bottom right.

MSVS may ask you to restart MSVS in admin mode.  If so, click the restart as admin option, wait for it to restart and then reattach the process.

**Comment by Hou5e** [comment]
I have both VS2015 and VS2022 installed. It looks like I should be using VS2015 for debugging the VC v14 that was used?

I had turned on the "fast" Testing WUs on one RG and left GPU folding running in a different RG on (2) PCs (one Windows, and one Linux). The onscreen GUI display of the log can't keep up and goes blank pretty quickly (within an hour with Windows and Firefox).

I had one error in about 2 hours, that was a bit different than the original error, where there was no message, and just crashed. I tried the VS2022 debugger and go this out of it, after the debugger wanted to load local source of file: SmartPointer.h from Cbang:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/4a31a488-3247-4972-b489-b32aecd82ee0)

---

Then restarting FAH v8.3.13 Debug on Windows, I got the original error in a few minutes. I clicked Retry to Debug, and using VS2015 this time, it came up with this: 
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/ae391001-7750-4ca1-8dfc-d7f3deb5264c)

When you go to step into it about 9-10 more times you get this:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/c0f99338-ae6e-4fcc-a6c0-006ebcb83a27)

Let me know if you would like to see something different.

**Comment by Hou5e** [comment]
For FAH v8.3.13 Debug on Windows, this would be a better screenshot of the Call Stack in VS2015 for the first error in the previous message:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/37a1ffde-d95a-4256-83bd-4177d83d7617)

**Comment by jcoffland** [comment]
I think this may be finally fixed in v8.3.14.

**Comment by Hou5e** [comment]
On FAH v8.3.14 Debug on Windows, I got one of these crashes so far between WUs for the Upload / Download events:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/0bdc796a-4292-49e9-872e-10a2c09f62c8)

Log File: [log-20240521-002936.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15382866/log-20240521-002936.txt)

![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/dadec209-a006-4480-91a1-a55f65b130e9)

**Comment by jcoffland** [comment]
This appears to be an issue with dangling pointer after one of the DNS servers provided by the system has failed.  Will be fixed in next release.

**Comment by jcoffland** [comment]
Is this finally fixed with v8.3.16?

**Comment by Hou5e** [comment]
I have not seen FAH crash with FAH v8.3.16 (Debug) on Windows, so I think it's fixed.
