### ISSUE TITLE
Remote client list is not updating on Windows

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#236]
The Remotes client list is not updating with v8.3.10 Debug, on Win10 (using Firefox). The FAH startup log has a lot of Remotes entries (~6000 in a few seconds) being added and removed, and the list of PCs is not showing the re-linked X99-12 PC on the Windows PC many hours later and after restarting FAH.
Afternoon log for today [log-20240511-004343.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/15281088/log-20240511-004343.txt)
This issue was also shown in the screenshots from 12 hours ago: https://github.com/FoldingAtHome/fah-client-bastet/issues/233#issuecomment-2104528413

**Comment by Hou5e** [comment]
It seemed like the list of linked PCs was out of sync or something back when this originally happened.

From the Linux PC a few days ago with FAH v8.3.10 Debug, I unlinked and had this message pop-up:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/d007564a-0248-4064-a31c-e5eb3e496ec4)
Then re-linkd the account and it was fine.

**Comment by jcoffland** [comment]
So this issue is fixed but there is likely another problem with machine (un)linking.

**Comment by kbernhagen** [comment]
I believe the accounts view is not reloading after a link/unlink button is clicked.
Maybe the client needs to echo something on the websocket connection?

Manual reload of page worked recently for me for a link action.
