### ISSUE TITLE
MacOS 14.5, FAH 8.5.3 Installation Failed

### ISSUE THREAD

**Issue by diskerror** [FoldingAtHome/fah-client-bastet#242]
I tried to install 8.3.5 on Mac Mini (M1, 2020, 8GB) with MacOS Sonoma 14.5 and received this message from the installer:

> **The installation failed.**
> The Installer encountered an error that caused the
> installation to fail. Contact the software manufacturer
> for assistance.

Thanks for your work!

**Comment by kbernhagen** [comment]
The macOS installer fails if your default web browser is Safari and one four known compatible browsers are not found in /Applications. 

This is in the important information panel in the installer. It is admittedly confusing and has been rewritten in the newer alpha releases.

**Comment by diskerror** [comment]
That worked. I installed Google Chrome and downloaded 8.5.3 with it.

Thanks
