### ISSUE TITLE
Add the max-units batch processing feature from the old client.

### ISSUE THREAD

**Issue by Shaeric** [FoldingAtHome/fah-client-bastet#243]
In the old client it was possible to configure processing of n-units before the program pauses.

This would be useful for more fine-grained control if time constraints exist.
A system that is otherwise needed during the day can comfortably fold multiple units during the night
instead of finishing only a single one.

What might also be worth considering to achieve a similar effect is a time gate.
For example, a user could decide that folding may start at 22:00PM and the last unit to process
before pausing may be requested at 05:00AM.

**Comment by jcoffland** [comment]
I believe this can be covered by https://github.com/FoldingAtHome/fah-web-client-bastet/issues/53.
