### ISSUE TITLE
Invalid user 'fah-client' - 8.3.5

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [FoldingAtHome/fah-client-bastet#248]
headless install on Ubuntu 18_04-lts

I'm used to using the latest stable release - I'm now trying out the 8.x version so my modified install code is likely poor.

Error msg:
```
Setting up fah-client (8.3.5) ...
install: invalid user ‘fah-client’
dpkg: error processing package fah-client (--configure):
 installed fah-client package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 fah-client
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

On at least 1 occasion, I did see a group called 'fah-client' - but not the user didn't exist

-- Install script --
```
sudo add-apt-repository -y ppa:graphics-drivers
sudo apt-get install -y nvidia-driver-430
sudo apt install -y ocl-icd-opencl-dev
sudo apt-get update

    # download and untar
echo apt-get install -y wget bzip2
sudo apt-get install -y wget bzip2 && \

echo sudo apt-get purge -y wget bzip2
sudo apt-get purge -y wget bzip2 && \

echo apt-get clean autoclean
sudo apt-get clean autoclean && \

echo sudo apt-get autoremove
sudo apt-get autoremove --yes && \

echo mkdir /etc/fah-client/
mkdir /etc/fah-client/

echo making config
sudo cat <<EOT >> /etc/fah-client/config.xml
<config>
    <account-token v="TOKEN REDACTED"/>
</config>
EOT

echo wget latest.deb
sudo wget https://download.foldingathome.org/releases/beta/fah-client/debian-10-64bit/release/latest.deb

echo install latest.deb
sudo apt install ./latest.deb
```

**Comment by Hou5e** [comment]
(I didn't try to reproduce this) But, are you having permission issues with the `config.xml` file (or the folder)?
I know FAH v8 doesn't work unless the permissions are set to the `fah-client-` user, like:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/97cdeb88-fd2c-4b49-8637-e5149b2138af)

Does the script work if you let the FAH installer run first to make the `/etc/fah-client/` folder and `config.xml` file, then afterwards rewrite the config XML settings to what you want them to be?

**Comment by kbernhagen** [comment]
Optionally creating `config.xml` before installing is the intended means of pre-configuring a new install.

The post install script will try to set owner and permissions.
https://github.com/FoldingAtHome/fah-client-bastet/blob/master/install/debian/postinst.in

**Comment by kbernhagen** [comment]
The pre install script tries to create the user and group.

**Comment by jcoffland** [comment]
Try the latest alpha, it's about to go beta anyway: https://foldingathome.org/alpha/

**Comment by marcosfrm** [comment]
The question is why `fah-client` user did not exist when postinst ran (failed at `install -d`). Should be created by preinst...

https://github.com/FoldingAtHome/fah-client-bastet/blob/master/install/debian/preinst

Can you purge fah-client and try again?

postinst will only change ownership of `/etc/fah-client/config.xml` when it does not exist (importing from v7, from `/var/lib/fah-client` or creating an empty config). Perhaps we could move down the `chown`/`chmod` calls to always run...

**Comment by jcoffland** [comment]
Please reopen if you can reproduce this on the latest client version.
