### ISSUE TITLE
Remove CUDA not supported message from AMD powered systems

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#250]
I just installed v8, launched it, logged in. checked the log without launching or downloading any projects or fahcores. Log has the following entry:
_14:21:54:W :CUDA not supported: failed to open dynamic library 'libcuda.so': libcuda.so: cannot open shared object file: no such file or directory_

My system is all AMD, there was never any nvidia hardware installed in it.
This existed in v7, too. It is time for this to be removed.

**Comment by kbernhagen** [comment]
Maybe the client could scan the pci bus before trying to load OpenCL and cuda libs? If it could determine there are no nvidia devices, it could not try to load cuda lib.

**Comment by jcoffland** [comment]
This is just cosmetic.  It may be annoying but the message is correct.  It just not worth adding a bunch of extra logic to the code to detect situations where CUDA is expected not to be there.

**Comment by muziqaz** [comment]
So you rewrite the client from ground up and put this in, and then don't bother removing, even though it makes no sense to have it in the first place? We have been asking for this crap to be sorted since early v7 days
It might be cosmetic to you, but it adds clutter and confusion to new users, and might bring unnecessary questions to those who will give support to them :/

**Comment by jcoffland** [comment]
What are you talking about.  Of course it has a purpose.  It's there to tell you CUDA is not found on that system.  What's the big deal?

**Comment by muziqaz** [comment]
The deal is that it adds clutter, unneccesary clutter, to already busy log files. Might as well add weather report to the log files, that will help the debugging process

**Comment by jcoffland** [comment]
Good idea.

**Comment by kbernhagen** [comment]
The only deal is that people sometimes post about it because it looks like an error.
