### ISSUE TITLE
NVidia GPU not detected by client after reboot.

### ISSUE THREAD

**Issue by skwysham** [FoldingAtHome/fah-client-bastet#252]
Restarting my laptop, either shutdown or restart from software updates, caused the gpu to be reported as "unsupported."  The telltale error message in the client log is:

[91m21:15:48:E :CUDA not supported: cuInit() returned 100[0m 

Those oddball characters are part of the message line.

Restarting the systemd service "cures" the problem.  This is a relatively recent, ~2-3 weeks, development AFAIK on my laptop.
[cuInit()_log_message.txt](https://github.com/user-attachments/files/15893623/cuInit._log_message.txt)

**Comment by jcoffland** [comment]
From the CUDA API documentation:

```
CUDA_ERROR_NO_DEVICE = 100
    This indicates that no CUDA-capable devices were detected by the installed CUDA driver. 
```

It sounds like your GPU was not available when the F@H client started.  Perhaps the drivers were upgraded on reboot.  Does it happen on every reboot or just after software updates?

BTW, those "oddball characters" are ANSI color codes.  Rendering them correctly depends on the tool you use to look at the log and your terminal settings.  For example if you run ``less /var/log/fah-client.log`` you will see those codes but if you run ``less -R /var/log/fah-client.log`` you should see a color coded log instead.  You can turn off log colors by adding the option ``<log-color v="false"/>`` to ``/etc/fah-client/config.xml``.

**Comment by skwysham** [comment]
No, no drivers were upgraded.  My hunch is that the folding service isn't responding to a power shutdown gracefully.

I surmise that those ansi characters meant "put this in red"

**Comment by jcoffland** [comment]
> No, no drivers were upgraded. My hunch is that the folding service isn't responding to a power shutdown gracefully.

I don't think that's the case.  Even if it were true there's no reason that should effect the GPU detection.  The client calls the CUDA API function ``cuInit()`` which returns 100 meaning ``CUDA_ERROR_NO_DEVICE``.  This means the CUDA driver, at the time the client calls it, believes the GPU is not there.  It could be that the F@H client is starting before something in the boot process that initialized the GPU.  We have seen a similar issue on Linux where suspending (or hibernating) a laptop causes it to come back with the GPU driver in a bad state.  This is not really a fah-client problem but a Linux/NVIDIA problem that effects the client.

> I surmise that those ansi characters meant "put this in red"

Yes

**Comment by skwysham** [comment]
Beh, also I need to run a health check on the ssd.....

**Comment by skwysham** [comment]
Maybe it's on "my end" of the network, since no one else is hollering.  I just saw this in the log (but everything is now tooting along)  after pausing folding, restarting my laptop, and starting folding again
  


  


  20:04:41:I2:<config/>
  
  20:04:41:I1:Opening Database
  
  ***@***.*** ID = ytUso-yZ2K0pPTLv8tuH38qq2OKGo0FNO1CksQK-VPc
  
  20:04:41:I3:Loading default group
  
  20:04:41:I3:Loading default resource group
  
  20:04:41:I1:Listening for HTTP on 127.0.0.1:7396
  
  20:04:41:I3:WU446:Loading work unit 446 with ID 1V0YoK80qyxDr7sAbSLFXXm6UKf2m6gTSqkDfmzzik4
  
  20:04:41:I3:WU449:Loading work unit 449 with ID phNR85ZAxxvs1yAluwAn2yWJ9bGR7ktQ4-lc--pg5Us
  
  20:04:41:I3:Loaded 2 wus.
  
  20:04:41:E :CUDA not supported: cuInit() returned 100
  
  20:04:41:I3:gpus = {
  
  20:04:41:I3: "gpu:01:00:00": {"vendor": 4318, "device": 8122, "type": "nvidia", "supported": false, "description": "TU117GLM [T600 Mobile]"}
  
  20:04:41:I3:}
  
  20:04:41:W :CON1:DNS lookup failed for api.foldingathome.org:443
  
  20:04:41:W :Failed to update GPUs
  
  20:04:46:I3:gpus = {
  
  20:04:46:I3: "gpu:01:00:00": {
  
  20:04:46:I3: "vendor": 4318,
  
  20:04:46:I3: "type": "nvidia",
  
  20:04:46:I3: "description": "NVIDIA T600 Laptop GPU",
  
  20:04:46:I3: "uuid": "8caf99dc-6582-8acc-abbd-3801a40f3bb9",
  
  20:04:46:I3: "cuda": {"platform": 0, "device": 0, "compute": "7.5", "driver": "12.2"},
  
  20:04:46:I3: "device": 8122,
  
  20:04:46:I3: "supported": true
  
  20:04:46:I3: }
  
  20:04:46:I3:}
  
  20:04:46:I3:Connecting to api.foldingathome.org:443
  
  20:04:46:I1:OUT2:> GET https://api.foldingathome.org/gpus HTTP/1.1
  
  20:04:48:I1:OUT2:< HTTP/1.1 200 HTTP_OK
  
  20:10:31:I1:REQ3:< GET /ping?_=1718827831473&callback=jQuery190037344596796856355_1718827831472 HTTP/1.1
  
  20:10:34:I1:Loaded cores/fahcore-a8-lin-64bit-avx2_256-0.0.12/FahCore_a8
  
  20:10:34:I1:Loaded cores/openmm-core-23/centos-7.9.2009-64bit/release/fahcore-23-centos-7.9.2009-64bit-release-8.0.3/FahCore_23
  
  20:10:34:I3:WU446:Running FahCore: /var/lib/fah-client/cores/fahcore-a8-lin-64bit-avx2_256-0.0.12/FahCore_a8 -dir 1V0YoK80qyxDr7sAbSLFXXm6UKf2m6gTSqkDfmzzik4 -suffix 01 -version 8.3.5 -lifeline 934 -np 14
  




  
    Stephen K Wysham
      
    
    "Most people would like to be delivered from temptation but would like it to keep in touch." -- Robert Orben
    
  




------ Original Message ------
   Received: 10:44 AM CDT, 06/19/2024

**Comment by jcoffland** [comment]
Could have been a driver/GPU hiccup.

**Comment by muziqaz** [comment]
The question is, why is fahclient insisting on downloading a GPUs txt file, when that system was folding fine before the reboot? I thought once fahclient has GPUtxt stored locally there shouldn't be any attempts to download a new copy, unless GPU in the system changed and old GPUtxt has no record of it, or there has been some changes to GPUtxt on server side and server is pushing it to the clients.
Another question is why fahclient is failing to connect (or resolve the DNS). We had some instances in the past where systems connected through wifi suffer from connectivity issues right after reboot, since fahclient starts before connectivity through WiFi has been fully established. So maybe this is the case too?

**Comment by jcoffland** [comment]
The client downloads a new GPUs.txt if the existing one is too old.

**Comment by muziqaz** [comment]
So any changes to GPUtxt server side will trigger the download?
I don't think anyone done any updates to that file recently.

**Comment by jcoffland** [comment]
No.  The client just downloads the latest once every 5 days.

**Comment by muziqaz** [comment]
Sorry to nag about this, but if during GPUtxt update, fahclient is unable to download new version while it still has old one stored locally shouldn't the client use the old version instead of just disabling a GPU because it couldn't get the latest version?

**Comment by jcoffland** [comment]
That's what it does.

**Comment by muziqaz** [comment]
> That's what it does.

That's not what it did in this case:
https://github.com/FoldingAtHome/fah-client-bastet/issues/252#issuecomment-2179413674
Or is that CUDA error not related to failed GPUs update?

**Comment by jcoffland** [comment]
Yeah, the error never had anything to do with GPUs.txt.

**Comment by skwysham** [comment]
So, presuming that a gpu is detected, what are the pitfalls to using whatever cpus.txt is available locally if the fah client has not changed since it was installed?

**Comment by muziqaz** [comment]
> So, presuming that a gpu is detected, what are the pitfalls to using whatever cpus.txt is available locally if the fah client has not changed since it was installed?
> […](#)
> On June 24, 2024 4:42:42 AM CDT, Joseph Coffland ***@***.***> wrote: The client downloads a new GPUs.txt if the existing one is too old. -- Reply to this email directly or view it on GitHub: [#252 (comment)](https://github.com/FoldingAtHome/fah-client-bastet/issues/252#issuecomment-2186065428) You are receiving this because you authored the thread. Message ID: ***@***.***>

There is no major pitfalls, in reality. We change some species designations from time to time, but those are usually announced in advance.
Other changes to GPUtxt is just adding new GPUs, nothing else, and if your GPU is already recognised, you are good to go and shouldn't worry about up to date version of GPU.txt
