### ISSUE TITLE
Windows FAH v8.3.17 probably has an excessive logging issue over time

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#253]
After running the Windows debug version of FAH v8.3.17, for the middle part of the day with 0xfe WUs for 2 hours a day, FAH just stopped and disappeared from the Windows System Tray after about 11 days. I don't remember seeing any error messages or log file errors (most likely happened when FAH was idle, and most likely at the Log Rotation time). I restarted FAH on June 20th, but it must have been running in the background still, and I missed finding and killing it until a day later. My only guess was the internal log file was getting excessively large. The internal log should probably get cleared once a week, if clearing it at the log rotation time is too often.

If the internal log not being cleared at some interval, there would have been about ~250 MB of log file text in memory in this case. If I had left this running for months, the internal log message size would have been really large:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/55c4afcb-6f9d-416e-929b-9dbfb4ab31b0)

Sorry, I don't have very much detail for this issue, but it did happen.
Let me know if anything else would be useful for fixing this.
I don't think most people would encounter excessive log file conditions often or quickly.

**Comment by jcoffland** [comment]
This wont happen if you don't run 0xfe.  By default the client keeps the last 90 logs and rotates once per day.  This can be changed with the options ``log-rotate-max`` and ``log-rotate-period``.  You can also turn on log compression with ``log-rotate-compression=bzip``.

So I believe this is already solved.
