### ISSUE TITLE
Don't show decimal ETA secs when ETA is less than a minute

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#26]

**Comment by kbernhagen** [comment]
This is not completed.
Did you mean to mark it `wontfix`?

I note the issue originates in cbang `TimeInterval::toString()`.
It is also responsible for incorrectly pluralizing days/hours/mins/secs when the value is exactly 1 with no leading zeros or decimal.

**Comment by kbernhagen** [comment]
Another WU now says `18 hours 54 secs | 88.2%`

**Comment by jcoffland** [comment]
Indeed.  Fixed with:

https://github.com/CauldronDevelopmentLLC/cbang/commit/6dcdf14e52205ed550f7c35f31ac2020811ec8da
