### ISSUE TITLE
v8.4 on Kubuntu/Mint/Debian/Firefox seems to not be working (Exception: Unexpected end of expression At: group.json:9:14)

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#260]
I updated to new alpha over v8.3.18 with apt. Browser shows no client version or any resource groups. Account settings also have no options to adjust anything local client related. Uninstalled new client, and reinstalled it again. No luck. restarted computer. Nothing. `systemctl` pretends there is no fah-client service to start or restart. `top` command shows no active fah-client process.
See screenshots attached. fahlogs have been generated, reporting `Exception: Unexpected end of expression At: group.json:9:14`.
Will switch to mint, and then debian in a sec to see how those work

[8.4 logs.zip](https://github.com/user-attachments/files/16325432/8.4.logs.zip)
![Account settings](https://github.com/user-attachments/assets/9ff3e595-1fd4-4000-a5c6-bec2c40975c6)
![main](https://github.com/user-attachments/assets/12762d74-9822-4b00-b94e-4f32658aa154)
![top](https://github.com/user-attachments/assets/4190b774-1ef8-4175-abe3-665a748bc7e5)

**Comment by muziqaz** [comment]
Same issue on Mint Linux. 2 fahlog files were created after installation, both end with json error

**Comment by jcoffland** [comment]
I believe this is caused by some corrupted builds on the Linux build machines.  Something similar occurred on my development machine.  I've done full rebuilds and republished the v8.4.0 packages and tested the build locally.  It should work now.
