### ISSUE TITLE
Try to keep `fahctl` compatible with Python 3.6

### ISSUE THREAD

**Issue by marcosfrm** [FoldingAtHome/fah-client-bastet#275]
Default Python version in RHEL 8 and openSUSE 15 is 3.6. Newer versions are available in separate packages, but the websocket-client module preset in the repositories is specifically packaged for the default version (installed in `/usr/lib/python3.6/site-packages/`). If it's possible without causing too much trouble, it would be interesting to maintain `fahctl` compatible with this version.

The current code seems to function correctly with Python 3.6, even though @kbernhagen specified a 3.8 requirement in commit 7904696bff9be65c7ecacb4817f1d8de26e8607e.

**Comment by kbernhagen** [comment]
My mistake. I see that a websocket-client 1.3.1 runs on python 3.6.

**Comment by kbernhagen** [comment]
I will make a PR.
