### ISSUE TITLE
v8.4.4 work units tab - active-only button 

### ISSUE THREAD

**Issue by bollix47** [FoldingAtHome/fah-client-bastet#280]
now the work units tab is showing all whether active or finished ... that has already reached numerous pages .... I only need to see the active ones on a regular basis and the history only when I want to look up something .... there is a Complete button but that just shows all the WUs with gold stars .... if that's not on then only the active units should display

this should probably be in fah-web-client-bastet issuses .... feel free to move it

**Comment by jcoffland** [comment]
Yes, this is the a Web Control issue.  But the I don't see the point of this.  The main machines page shows the active WUs.  Why would the WUs history show only the same information by default?  Please feel free to open an issue fah-web-client-bastet issue if you can better explain why this is necessary.

**Comment by bollix47** [comment]
because in 8.4.4 I do not see any WUs in the main machines tab .... only the actions but the WU info is blank

**Comment by muziqaz** [comment]
But that is a separate issue. `Machines` tab should be showing all the currently running WU/Resource Group info. If it is not something is broken
