### ISSUE TITLE
Don't allow invalid machine-name in config.xml

### ISSUE THREAD

**Issue by tabasavr** [FoldingAtHome/fah-client-bastet#282]
Currently it is possible to set an invalid `machine-name` in `config.xml` and the client will silently accept it. Not sure if it was the reason of my problems (https://github.com/FoldingAtHome/fah-client-bastet/discussions/214#discussioncomment-10518054), but I'd expect some indication of an invalid name just like in the web client

**Comment by jcoffland** [comment]
Fixed in v8.4.5

**Comment by kbernhagen** [comment]
Now the client crashes at startup if `machine-name` is invalid.
It might be reasonable to replace invalid characters with `-` and continue.

**Comment by jcoffland** [comment]
By crash you mean it exits with an exception, right?  This is perfectly acceptable if you're modifying the ``config.xml`` or command line parameters.

**Comment by kbernhagen** [comment]
Yes, I expect it is by exception.

I was trying
https://github.com/linuxserver/docker-foldingathome
and had a space in the MACHINE-NAME env variable. I had a tough time figuring out why the client was not running.

I eventually found the right system/docker log with the clue.
