### ISSUE TITLE
v8.4.4 web viewer of another folding computer always shows 100% progress, regardless of actual progress.

### ISSUE THREAD

**Issue by ElectricVehicle** [FoldingAtHome/fah-client-bastet#284]
v8.4.4 web viewer of another folding computer always shows 100% progress, regardless of actual progress.

Viewing my Ubuntu folding computer from Chrome (Version 128.0.6613.120 (Official Build) (64-bit)) on a Windows 11 computer:

Note the ETA shows 35 minutes so it is definitely not 100% done.
Web viewer on the Ubuntu folding computer (local) shows the correct % progress.

Most current log lines:
Start of WU:
23:04:36:I1:WU5463:Project: 16771 (Run 35, Clone 4, Gen 23)
....time passes....
Latest log lines (within 5 minutes or so of screen shots):
23:45:20:I1:WU5463:Completed 1500000 out of 2500000 steps (60%)
23:45:21:I1:WU5463:Checkpoint completed at step 1500000
23:46:02:I1:WU5463:Completed 1525000 out of 2500000 steps (61%)

![Screenshot 2024-09-08 163711](https://github.com/user-attachments/assets/e8e01e69-dae6-445f-a0eb-2e74941d6040)
![Screenshot 2024-09-08 163759](https://github.com/user-attachments/assets/f751a138-8424-4d57-a52d-51ba0739bfdd)

Ubuntu 22.x folding computer:
05:55:49:I1:***************************** System ******************************
05:55:49:I1: CPU: Intel(R) Core(TM) i7 CPU X 980 @ 3.33GHz
05:55:49:I1: CPU ID: GenuineIntel Family 6 Model 44 Stepping 2
05:55:49:I1: CPUs: 12
05:55:49:I1: Memory: 11.67GiB
05:55:49:I1:Free Memory: 7.05GiB
05:55:49:I1: OS Version: 6.8
05:55:49:I1:Has Battery: false
05:55:49:I1: On Battery: false
05:55:49:I1: Hostname: HexaMonster
05:55:49:I1: UTC Offset: -7
05:55:49:I1: PID: 6116
05:55:49:I1: CWD: /var/lib/fah-client
05:55:49:I1: Exec: /usr/bin/fah-client

**Comment by kbernhagen** [comment]
You need to use
https://v8-4.foldingathome.org/

**Comment by kbernhagen** [comment]
The alpha and beta site should probably always redirect.

**Comment by ElectricVehicle** [comment]
Thanks @kbernhagen ! https://v8-4.foldingathome.org/ works and resolves the issue.

Where would I have found that? Should it be added to https://github.com/FoldingAtHome/fah-client-bastet/blob/master/TESTING.md ?

Is there a forum / discord / slack for the alpha client that I should join?
I don't know if I should discuss the alpha clients in the public https://foldingforum.org/ ?

Does the alpha client use the same QRB as the full releases do?

**Comment by kbernhagen** [comment]
Discord: http://discord.gg/foldingathome

Discussions: https://github.com/FoldingAtHome/fah-client-bastet/discussions
See Testing discussion for Alpha

For Beta and Release, see FoldingForum.org as usual

**Comment by ElectricVehicle** [comment]
Thanks @kbernhagen !

I'm closing this issue as user education. I have just been educated! Thanks!

**Comment by jcoffland** [comment]
I've made https://alpha.foldingathome.org redirect to https://v8-4.foldingathome.org.
