### ISSUE TITLE
Save the logs for failed WUs with log management.

### ISSUE THREAD

**Issue by ElectricVehicle** [FoldingAtHome/fah-client-bastet#285]
Save the logs for failed WUs and a way to view them with log management to prevent filling up the disk.

Maybe something like:

- Limit to 10? MB max of total saved log files.
- The saved logs must persist across restarts of FAH, restarting the computer etc.
- When saving a failed WU log, include the immediately preceding good WU log (if any). This is tremendously useful to compare good vs. bad to find the problem, especially for people who are less familiar with the logs.
- Save the logs for the first 10 failed WUs in xx (30?) days (Sometimes the original failure has the failure information and then subsequent failures are a result of the first one but don't fail for the original cause...)
- Save the logs for the last 10 units in xx (30?) days (Sometimes the original failure was fixed sometime ago but a new failure is occurring within the xx (30?) days)
- Don't purge the failed logs when they age out, only purge them when another eligible failed log needs to be saved.
- Provide a button or other means for the user to clear that failed logs in preparation for the next WU failure

To wit - this happened to me and I have no way of fixing what went wrong because all the logs are gone. Note the 8.4.4 delay between failed WUs helps to keep from trashing so many WUs, but there's still a need to preserve logs from failed WUs.
v8.3.5 client rapid dumping of WUs ruined my folding user
https://foldingforum.org/viewtopic.php?p=365434#p365434

**Comment by ElectricVehicle** [comment]
Ahh, thank you! Closing this issue.

**Comment by kbernhagen** [comment]
Use `fah-client --help` to see some log options you can put in `config.xml`.
Don't be deceived about the xml format.
For example, `log-rotate-max` of 100 files would be `<log-rotate-max v="100"/>`
