### ISSUE TITLE
Latest Alpha does not start with Windows 10 upon system restart

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#286]
It did auto start when I installed it, but today I got Windows update notification pop up, so I restarted the PC, and fah is not running when Windows loaded.
I did not exit FAH before reboot. There is no FAH related processes in Task Manager. Start with windows was ticked during installation.
Windows 10.

**Comment by kbernhagen** [comment]
Someone else claimed it does work if it was an upgrade install from v7.

**Comment by muziqaz** [comment]
Actually FAH is completely dead on that restart. I can't even start it from shortcuts and even program files foldingathome.exe fails to start it. If I double click the exe file windows console shows up for split second with lines and lines of Unknown Exception.
Logs are not showing any of that unknown exception spam.

Is it possible that stupid Windows Update just outright killed everything FAH related, process wise, and proceeded with its own rebooting business?

OK, restarted PC again. FAH did not start. Upon doubleclicking exe file, command line printed 3 lines of Failed to open something something, Access Denied (sorry command line closes very quickly), and any other doubleclicking attempt after that launches cmd briefly with unknown exception spam.
So when I installed this client, I did not change fahdata folder, left it default, which is ProgramData folder. Might there be the case of permission issue which we used to see randomly with other people who left fahdata folder as default folder (that was even the case with v7)?

**Comment by muziqaz** [comment]
> Someone else claimed it does work if it was an upgrade install from v7.

It was upgrade install over v7

**Comment by muziqaz** [comment]
I reinstalled the client, and after installation client started straight away. It is late right now, but sometime this week I will play around with this a bit more.

**Comment by muziqaz** [comment]
Wiped the progress of the GPU and CPU projects too :(

**Comment by jcoffland** [comment]
I just tested this and F@H restarted just fine.  It took a little while after the reboot but it started.

**Comment by muziqaz** [comment]
I'm going on annual leave next week, so I will test this extensively with win 10 and 11 on my machines. I do not restart my machines too often. 
Linux seem to work fine on my end.

**Comment by muziqaz** [comment]
OK, just restarted Win11 and also Win 10 machines, which have v8 installed. Both failed to start upon system restart. I'm 12minutes in right now, and it is still not launched. Both are showing as Disconnected when I look at them through remote monitoring.
Here is the screenshot of event viewer which has entry related to fah (top entry in the screenshot).
![fah win11 fail to start](https://github.com/user-attachments/assets/37aa1a2b-033e-4a25-abdd-608f8b234a7c)

It is same exact Event Viewer entry I see on Win 10 machine, too.

And when I try to start from shortcut, I get nothing, and Event Viewer reports with the same entry as above.
I left default installation options on both machines, so both have fahdata folder in ProgramData directory.
Nothing special was done to any of the Windows installations.

FAH logs are not reporting anything. They just show stop in folding when I am restarting the PCs

**Comment by muziqaz** [comment]
Both PCs started new WU ignoring old one :(
OK, after editing the security options for the folder and restarting FAH started fine. 

However, v8 again ignored WU downloaded before restart, and downloaded new one again. So in my case every time I restart a PC with running or paused WU, that WU is ignored and v8 downloads new WU. I can still see old WU's directory in `Work` folder, now I have 5 of them while I am only folding on one resource group.
This is happening on both, Win 11 and Win 10 systems of mine.
After Security "tweak", there is no more errors in Event Viewer. FAH just forgets that it was folding a WU before restart

**Comment by jcoffland** [comment]
So it's not starting because it does not have permission to write to the ``log.txt`` file.  Is there anything non-standard about your install?  Did you install in a different directory or choose non-default install options?

**Comment by muziqaz** [comment]
> So it's not starting because it does not have permission to write to the `log.txt` file. Is there anything non-standard about your install? Did you install in a different directory or choose non-default install options?

Yes, it seems that event viewer is suggesting fahclient failing to open log.txt.
My installations are (on purpose) standard. data folder is in `ProgramData` directory. And I have never touched anything in regards to windows permissions for `ProgramData` folder. Also, 2 different machines with different windows installs are having same reaction

**Comment by jcoffland** [comment]
I just talked to someone else who is having this problem.  The issue is that the ``Users`` group is lacking write permission on ``C:\ProgramData\FAHClient`` and ``C:\ProgramData\FAHClient\log.txt``.  I'm not sure how this gets set incorrectly.  On my Windows 10 VM the ``Users`` group does have write permissions.  I believe you can work around this by manually granting ``Users`` write permissions to this directory and file.

We need to modify the Windows installer to make sure this directory gets the correct permissions.

**Comment by muziqaz** [comment]
Permissions are now added upon fah installation. normal system user now has full control of FAHClient folder inside of ProgramData directory.

**Comment by muziqaz** [comment]
Restarting Windows PC now starts FAHClient, too.
Thank you
