### ISSUE TITLE
Blue Pause All button does not work

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#289]
When clicked on `Pause All`, web control refreshes, for split second all machines are shown as disconnected, then refresh again, and all machines showing as normal, and all WUs are chugging along as normal, even the ones which were set to finish. This is from Windows 11 Firefox machine. Local machine also stays folding.

Mint Linux machine only pauses local client with Pause All, while remote clients show up Disconnected briefly, then come back to normal and keep folding with status unchanged.

This was the issue with 8.4.4 too. Only found out today when wanted to pause everything for new client update. 8.4.5 is acting the same

**Comment by jcoffland** [comment]
I'm not able to reproduce any of this.  The pause button appears to be working fine in Firefox on Linux and Windows.

**Comment by muziqaz** [comment]
Hm, it is working fine right now. Is it possible that was caused by my other issue, the one which I send you through DM? With web control window twitching, due to some connectivity issues.
I will close this issue, but will keep an eye out, and try Pause all once in a while
