### ISSUE TITLE
[fah-client v8.3.18; arm64 linux 6.1.0] OpenCL not supported error / headless client not fetching work

### ISSUE THREAD

**Issue by catleeball** [FoldingAtHome/fah-client-bastet#298]
## Issue

Hi team! I'm migrating a headless VPS instance from the old v7 client and struggling to get fah-client to fetch work. I was testing this by running `fah-client --config /etc/fah-client/config.xml` after updating the config file.

I suspected it might be related to a warning I saw in the logs `W :OpenCL not supported: clGetPlatformIDs() returned -1001`, but wasn't sure if that was strictly needed for running only on CPU.

~~Another interesting note: the logs say that the platform is `linux 5.10.0-15-arm64`, but `uname -a` says it's a more recent kernel: `Linux phx 6.1.0-26-arm64 #1 SMP Debian 6.1.112-1 (2024-09-30) aarch64 GNU/Linux`~~

I also tried connecting to the HTTP configuration via reverse proxy, but the web interface only shows "No folding machines found. Login or install the Folding@home client software." even when confirming that `fah-client` is running and its logs show the HTTP get request.

## Details

**Log**

- https://gist.github.com/catleeball/a78bd84a847a7a0d96c80c5ba952fea7

**Config**

```
<config>
	<cpus v="4"/>
	<user v="catleeball"/>
	<passkey v="redacted"/>
	<machine-name v="phx"/>
	<allowed-origins v="https://v8-3.foldingathome.org/ http://localhost:7396 http://100.65.233.27:7396"/>
	<http-addresses v="127.0.0.1:7396 100.65.233.27:7396"/>
</config>
```

**Machine details**

`uname -a`
> Linux phx 6.1.0-26-arm64 #1 SMP Debian 6.1.112-1 (2024-09-30) aarch64 GNU/Linux

`clinfo`
> Number of platforms                               0
> 
>ICD loader properties
>  ICD loader Name                                 OpenCL ICD Loader
>  ICD loader Vendor                               OCL Icd free software
>  ICD loader Version                              2.3.1
>  ICD loader Profile                              OpenCL 3.0

`lscpu`
- https://gist.github.com/catleeball/306dfb984d7cb895e85e9fe41d984951

Web interface over reverse proxy error
![Web interface over reverse proxy error](https://github.com/user-attachments/assets/62720aa1-6ffd-4586-8ff8-8f169e25885a)

VPS is Oracle Cloud's ARM free tier.

---

Please let me know if you need any more info! Thank you!

**Comment by kbernhagen** [comment]
`Platform` in the logs refers to the build machine.

**Comment by jhitze** [comment]
@catleeball I ran into this issue today as well. I think this is a missing-documentation error.

I am running it on a headless ubuntu 22.04.

I ended up adding the token to the config file and it started right up and showed up in the remote [web client](https://v8-3.foldingathome.org/machines).
```<account-token v='redacted'```
