### ISSUE TITLE
E: WU352: Exception: Unexpected end of expression

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#302]
Saw this error. Not sure what it is
![unexpected end of expression](https://github.com/user-attachments/assets/1ca763e5-c028-4741-b742-ff9d6d8053b8)

Regards

**Comment by jcoffland** [comment]
That means the client failed parsing the JSON visualization file.  Likely it's an incomplete file.  It should not be a big problem.  Either the core is still writing to the file or the core crash while writing the file.
