### ISSUE TITLE
How to build Folding@Home from source for Linux?

### ISSUE THREAD

**Issue by Myron472** [FoldingAtHome/fah-client-bastet#306]
I haven't found anywhere on the internet how to build FAH from source. I really would like to use new 8 version on my Fedora Linux, however, there is no rpm package for it currently.

**Comment by muziqaz** [comment]
@marcosfrm you had some guides done somewhere, didn't you?

**Comment by marcosfrm** [comment]
https://github.com/FoldingAtHome/fah-client-bastet/blob/master/BUILDING-RPM.md
