### ISSUE TITLE
Cannot make RPM package

### ISSUE THREAD

**Issue by Myron472** [FoldingAtHome/fah-client-bastet#310]
I am using Fedora 41 and tried to build FAH following the BUILDING-RPM.md. I created folder **fah-building** and cloned cbang and fah-client-bastet repos to it via `git clone`. Then I ran these commands, provided in the file:
```
export CBANG_HOME=$PWD/cbang
scons -C cbang
scons -C fah-client-bastet
scons -C fah-client-bastet package
```

First three commands were executed successfully without any errors. But when I ran `scons -C fah-client-bastet package`, I got this error:
```
+ cp -a . /home/glyder/fah-building/fah-client-bastet/build/BUILD/fah-client-8.4.8-build/BUILDROOT
cp: cannot copy a directory, '.', into itself, '/home/glyder/fah-building/fah-client-bastet/build/BUILD/fah-client-8.4.8-build/BUILDROOT/.'
```

**Comment by Myron472** [comment]
Update:
I tried to build FAH on pure Fedora 41 that I installed in a a virtual machine. Did the same steps as I did before and got exactly the same error. 
So the problem is definetely not in my local configuration of Fedora.

Also could you explain what this line of code (cp -a ...) should actually do? As I understood, the `cp -a` command (*a* for *archive*) tries to recursively copy the folder it is located in into the `/home/glyder/fah-building/fah-client-bastet/build/BUILD/fah-client-8.4.8-build/BUILDROOT` but this directory happens to be the directory the compiler is located in so scons throws an error.

Also I found some interesting thing after I tried to create the package - if you go to `fah-client-bastet/build/BUILD/fah-client-8.4.8-build`, you'll see two folders: `BUILDROOT` and `SPECPARTS`. In the `BUILDROOT` folder there are also `BUILDROOT` and `SPECPARTS` folders.
Maybe this is some kind of a bug that happens because there are two `BUILDROOT` folders in the path?

**Comment by marcosfrm** [comment]
This is RPM 4.20 breakage. I'll fix it soon in cbang.

**Comment by marcosfrm** [comment]
Please try https://github.com/CauldronDevelopmentLLC/cbang/pull/166

**Comment by Myron472** [comment]
Thanks! RPM was build successfully with the provided version of cbang 👍
