### ISSUE TITLE
Web Client does not show work units (Visual bug) 

### ISSUE THREAD

**Issue by Myron472** [FoldingAtHome/fah-client-bastet#311]
I have fah-client version I've built from source (rpm package). At first, client started normally and FAH web control opened. I logged into my account, set it up and ran work. Through the console (Work Unit log) I can see that client is working and computing results. But web control does not show progress bars for some reason:
![FAH-WebClient-visual-bug-rpm](https://github.com/user-attachments/assets/47ece3f1-abd3-4ad9-a34b-308de47bd9af)

**Comment by muziqaz** [comment]
Update your Megabook to 8.4 and then use URL: v8-4.foldingathome.org to monitor your clients

**Comment by Myron472** [comment]
Ah, yes, how could I miss that. Thanks!
