### ISSUE TITLE
Implement the ``fold-anon`` feature from the old client.

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#32]
Set default paused true

This will give a user ample time to configure the client before it starts on first run.
There is no need for a pause until configured mechanism.
Defaults will seldom be what a user wants.
Many people are dismayed when fah "takes over" their machine immediately upon install.
Support burden on foldingforum.org may be reduced.

**Comment by jcoffland** [comment]
This doesn't work well for mass installs.  The old client waits for a few minutes for the user to enter user info before automatically starting if it's not already set.  I suppose we may need this feature in the new client.

**Comment by kbernhagen** [comment]
Mass installs can just create a config.xml with paused false. 


On Feb 20, 2022, at 12:07 PM, Joseph Coffland ***@***.***> wrote:

﻿
This doesn't work well for mass installs. The old client waits for a few minutes for the user to enter user info before automatically starting if it's not already set. I suppose we may need this feature in the new client.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kbernhagen** [comment]
If it defaults to paused true, you don't need the wait for config feature, nor fold-anon.

**Comment by jcoffland** [comment]
Yes, I like less code.  Setting ``paused=true`` by default benefits existing users who are reinstalling, which is good.  But for new users they will likely wonder why nothing is happening when they first install F@H.  Also, complicates mass installs if you have to ship a ``config.xml``.

One alternative is to ask for a user name, team and passkey in the installers but then we have to implement that logic three different ways.  I think the more complicated path is necessary here to satisfy all the different types of users at once.

**Comment by kbernhagen** [comment]
Windows and macOS users will be presented with a frontend web page when the install finishes or client starts. Doesn’t matter if they’re new or upgrading. 

I think it’s much better to never start folding without a user clicking start. 

Once unpaused, the client will remember the setting.

**Comment by kbernhagen** [comment]
There have been enraged people posting on foldingforum about the software taking over their machine. Some play whack-a-mole trying to kill the client, which just respawns. Makes them angrier.

**Comment by kbernhagen** [comment]
If you do the simple thing of default paused true and wait for alpha tester feedback, you should also pick up paused from ``config.xml`` so people can use an explicit paused false there for mass installs and containers.

**Comment by jcoffland** [comment]
This has been implemented.
