### ISSUE TITLE
Changing CPU count pauses job or spawns new jobs

### ISSUE THREAD

**Issue by Justin-J-Miller** [FoldingAtHome/fah-client-bastet#39]
### Your Environment
- F@H Software version: V8.0.1
- Operating System: Ubuntu 20.04.3 LTS
- CPU-ntel(R) Core(TM) i7-6800K CPU @ 3.40GHz, No OC     
- Browser: Mozilla Firefox 97.0 64-bit

### Expected Behavior
Expected changing CPU core count to reduce the number of CPUs dedicated to folding.

### Current Behavior
Reducing the number of CPUs available to folding pauses the job with the error "Resources not available". 
Similarly, enabling GPU based folding pauses existing WUs.

### Steps to Reproduce
1. Fresh installation of V8.0.1 all defaults enabled
2. After installation, start F@H and select "configuration"
3. Acquire a job from the server
4. Reduce the number of available CPUs and click "save".
5. Returning to "Home" indicates the WU is paused. This is also observable through the terminal using "top".

### Possible Solution
Would be great to have WUs only pause if users set a CPU count below the CPUs specified in the assignments constraints. Perhaps if the user does this, an error message could pop up indicating they are unlikely to finish the job before the timeout?

**Comment by Justin-J-Miller** [comment]
### Followup observation
Starting a WU with a low number of cores (e.g. 6) and then raising the number of CPUs available downloads a _new_ WU instead of upping the CPU count for the existing job. New job uses the specified number of CPUs minus the existing job CPUs.

### Steps to Reproduce
1. Start a job with less than maximum CPU count
2. On configuration tab, increase the number of CPUs available, save settings
3. Returning to "Home" tab indicates that multiple jobs are "running"/queued

### Possible Solution
I think ideal to have the specified CPUs assigned to a single WU and just have the WU utilize more/less CPUs accordingly. New jobs should probably not be spawned with `Specified CPUs - Existing CPUs` as this will result in potentially very slow WU completion.
![image](https://user-images.githubusercontent.com/66532328/155372571-6e670114-9f57-46c1-a73d-cb09c90a48e4.png)


![image](https://user-images.githubusercontent.com/66532328/155372528-af8df610-b87a-441c-868f-bf7293cb74e2.png)

**Comment by jcoffland** [comment]
This is the intended behavior. It's actually a bad idea to change the number of CPUs in the middle of a WU run.  It can lead to failures or corruption of the data.  For this reason, we no longer allow it.  So if you change the number of CPUs available the client will decide the best course of action.

**Comment by PantherX** [comment]
I personally think this is a regression, i.e. the client should finish the existing WU with the original number of CPUs and then the new WU downloads runs on the specified threads. A message could pop-up with "You have changed the CPU count and it will take effect when the next WU is downloaded" which is more user-friendly and benefits science as WUs are returned ASAP :)

**Comment by jcoffland** [comment]
That doesn't really help with the situation where someone needs more CPU power for something else right away.
