### ISSUE TITLE
No bonus point for WU finished properly. Passkey OK

### ISSUE THREAD

**Issue by Adanorm** [FoldingAtHome/fah-client-bastet#48]
Hello,

Currently trying this new client. 8.1.2
My setup : virtual machine with 8 cores, 16 GB ram. Ubuntu desktop 22.04 fresh install

Passkey setted properly.
Finished the WU 

![2022-10-07_095039](https://user-images.githubusercontent.com/46302945/194763712-eb3dd89b-0b83-4ab2-a6fa-69f61c57fb59.png)

Result on stats server : 
Hi toTOW (team 51), Your WU (P16984 R86 C1 G86) was added to the stats database on Sun, 09 Oct 2022 06:04:41 GMT for 54550 points of credit.

This is base credit, passkey seems to be ignored.

**Comment by jcoffland** [comment]
This is a known problem.  The issue is with the Work Servers (WS) and it affects all v8 clients.  The WS will be upgraded soon.

**Comment by kbernhagen** [comment]
Do the Collection Servers run the same software as the WS?

**Comment by jcoffland** [comment]
Yes

**Comment by jcoffland** [comment]
Fixed
