### ISSUE TITLE
Repeated ``Failed response: EOF`` when trying to download WU on Windows

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-bastet#52]
Originally reported here: https://github.com/FoldingAtHome/fah-web-client-bastet/issues/46
[log_2022-11-15_01.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/10012493/log_2022-11-15_01.txt)

The log file below, has the GPU slot failing to get work on a new Windows install. It had no existing settings, so I paused it, and setup my user info and enabled the GPU. Not sure if this was just bad AS luck, but it seemed like an error, and not what you want new users seeing when their first startup.

```
08:52:47:I1:WU2:Retrying in 8 mins 32 secs
09:01:19:I1:WU2:Downloading WU
09:01:19:I1:OUT18:> POST https://pllwskifah1.mskcc.org/api/assign HTTP/1.1
09:01:19:I3:Connecting to pllwskifah1.mskcc.org:443
09:01:19:E :WU2:Failed response: EOF
09:01:19:I1:WU2:Too many retries, failing WU
```

**Comment by jcoffland** [comment]
I've seen something similar.  I have Windows in a VM and the client is unable to connect to F@H at all.  Every attempt fails with ``Failed response: EOF``.  There may be a timing sensitive bug in the event driven networking code used in v8.  The problem also occurs for me with v8.1.2.

**Comment by jcoffland** [comment]
I believe this was a WS issue.  Reopen if it reoccurs.

**Comment by hucker75** [comment]
I'm getting this today.  I've not run Folding for a couple of weeks, and just put many computers with GPUs back on.  They're getting the above message repeatedly, before eventually getting a workunit.  Does EOF mean "no work available"?

`05:50:39:I1::WU374:Requesting WU assignment for user PeterHucker_GRC_53ed9d9b7d568cb7eb1ccc25a7dc4492 team 224497
05:50:40:I1::WU374:Received WU assignment ZjNtx2o8lE5w-5eCeG4DtyKZBTkyxw3bNUWrUZTDcLQ
05:50:40:I1::WU374:Downloading WU
05:50:40:E ::WU374:Failed response: EOF
05:50:40:I1::WU374:Retry #1 in 2 secs
05:50:42:I1::WU374:Downloading WU
05:50:42:E ::WU374:Failed response: EOF
05:50:42:I1::WU374:Retry #2 in 4 secs
05:50:46:I1::WU374:Downloading WU
05:50:46:E ::WU374:Failed response: EOF
05:50:46:I1::WU374:Retry #3 in 8 secs
05:50:54:I1::WU374:Downloading WU
05:50:54:E ::WU374:Failed response: EOF
05:50:54:I1::WU374:Retry #4 in 16 secs
05:51:10:I1::WU374:Downloading WU
05:51:10:E ::WU374:Failed response: EOF
05:51:10:I1::WU374:Retry #5 in 32 secs
05:51:42:I1::WU374:Downloading WU
05:51:42:E ::WU374:Failed response: EOF
05:51:42:I1::WU374:Retry #6 in 1 min 4 secs`

**Comment by jcoffland** [comment]
EOF does mean End of File in this case.  It indicates either a network problem or a Work Server issue.  Most likely the former.  I cannot check the server because I don't know which project your machine was assigned to.

``HTTP_SERVICE_UNAVAILABLE`` means there are no available WUs for that project.  This can happen if the project gets over assigned which only happens when it's nearly out of WUs.

>  (Sorry about the mangled paste, I put it in "code" but Github seems to be ignoring the carriage returns).

You need to use three tick marks on each end.  See my edit to your message above.

**Comment by hucker75** [comment]
I'll assume something on the network is overloaded somewhere (at the Folding end presumably, nothing else is slow for me)?

I just pressed the code button, is this a Github bug?  If it needs three ticks, the button should put them in.

**Comment by jcoffland** [comment]
I think you're right.
