### ISSUE TITLE
Restarting Client, the WU ETA completion is inaccurate

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-bastet#57]
From: https://github.com/FoldingAtHome/fah-web-client-bastet/issues/57

@Hou5e wrote:
After restarting the Client, with a partially completed WU (like at 50% or more completed), the WU ETA completion is inaccurate and says 5-15 minutes left for about 1 hour, on a 2 hour long GPU WU. The displayed ETA time does odd things, like: stops, and jumps around.

**Comment by jcoffland** [comment]
The ETA is computed as: ``run_time_estimate * (1 - estimated_progress)``.  Run time is estimated from first from previous runs of the same WU, second from timings of previous frames and finally from the ``timeout`` if no previous information is available.  Progress is estimated based on the number of frames completed plus an estimate of how long the current frame has progressed.  This can lead to inaccuracy in several ways.

A big part of the problem is that current cores don't give very accurate progress information.  This should improve with future core releases.  The one thing we can measure fairly accurately is how much time a WU has run for.  But performance can vary especially if other tasks are running on the same CPUs/GPUs.

The relevant code starts here: https://github.com/FoldingAtHome/fah-client-bastet/blob/master/src/fah/client/Unit.cpp#L213

**Comment by Hou5e** [comment]
Linux Mint 21.1 (U22.04), FAH Client v8.1.6: Just adding a screenshot for GPU WUs that have about 20 minutes left to complete, where the GUI says ~30 seconds left, about a minute after restarting FAH Client, with the partially completed work:
![image](https://user-images.githubusercontent.com/20870053/209616698-6c680ee0-3825-43e2-9287-7754d9b921db.png)
