### ISSUE TITLE
Add bool option allow-remote-control

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#63]
If true, have client add "0.0.0.0:7396" to http-addresses when evaluated. Do not save this.

Yes, I know this requires a client restart when toggled.

Web Control can provide a checkbox for this option, and include an explanation and warning about what it does.

If true and allow/deny are default "0/0" and "", maybe on startup use, without saving,
```
<allow v='127.0.0.1 10.0.0.0/8 192.168.0.0/16 172.16.0.0/12 169.254.0.0/16'/>
<deny v='0/0'/>
```
I believe that matches all non-routable IPv4 addresses.

This may be enough to satisfy the desire by many for easy remote control. 
It would still be localhost-only by default.

**Comment by kbernhagen** [comment]
`allow-remote-control` would be stored in `./client.db`, but get its first-run value from `config.xml`.

If there is anything that causes `config.xml` writes, it might be helpful to have a dummy class that just registers the unused v7 options. That way, any v7 options would not be lost when `config.xml` is written. For those who might want to revert to v7 while it is still supported.

**Comment by kbernhagen** [comment]
Or the client could copy `config.xml` to `config8.xml` on first-run and use that.

**Comment by jcoffland** [comment]
Not relevant now that we have F@H accounts.
