### ISSUE TITLE
Allow equivalent allowed-origins to connect to http server

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#69]
Currently, these are all considered different and require an exact match:
```
https://app.foldingathome.org

http://localhost
http://localhost:7396
http://127.0.0.1:7396

http://sanctuary
http://sanctuary:7396
http://sanctuary.local:7396
http://sanctuary.local.:7396
```

The port should be optional and assumed to be a relevant port in `http-addresses`.
Or any port could be allowed, since to connect at all it must already be in `http-addresses`.

**Comment by kbernhagen** [comment]
When evaluating an origin, I would suggest
- strip port
- strip any trailing dot
- strip suffix ".local"
- treat localhost as "127.0.0.1"

**Comment by jcoffland** [comment]
I'm not planning to peruse features for direct connection to clients now that we have F@H accounts and connection via F@H node.
