### ISSUE TITLE
Load SSL certs from OS on Windows and OSX

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-bastet#8]
@kbernhagen wrote:
> Found this post, that indicates that possibly only one callback needs to be implemented to integrate with apple’s security api. 
>  https://stackoverflow.com/a/15341662
> On Windows, OpenSSL has a built in engine for Microsoft crypto api. One needs to tell OpenSSL to load the engine and use it.

**Comment by kbernhagen** [comment]
Apple's OpenSSL 0.9.8 with integration patches:
[https://opensource.apple.com/source/OpenSSL098/OpenSSL098-80/](url)

**Comment by kbernhagen** [comment]
This may be done.

However, the certs returned on Windows by CertOpenSystemStoreA() may need to be validated before adding them to the openssl trusted store.
