### ISSUE TITLE
Finishing WU becomes paused-by-user instead of waiting for idle system

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#83]
macOS 10.14 fah 8.1.7

Configured client to Fold When Idle.
Started
Once idle, WU downloaded and went to Running
Clicked Finish
WU was Finishing
User logged in, ending system idle
WU went straight to Paused by user
Clicked Start
WU went to Waiting for idle

I think Finishing needs to be preserved when a pause is temporary.

Maybe there need to be multiple pause flags,
or an ephemeralPause flag.

Any pause-on-battery will also need this.
Either its own flag, or a bit mask in a flag.

**Comment by kbernhagen** [comment]
This switch to paused does NOT seem to happen on macOS 12.6.2.

I need to test more.

**Comment by kbernhagen** [comment]
I was wrong. It IS happening on macOS 12.

You can also see this if you
- config RG to Fold When Idle
- it goes to Waiting for idle
- click Finish for RG
- it goes to Paused by user.

**Comment by kbernhagen** [comment]
Finishing has generally lost its "stickiness".

**Comment by kbernhagen** [comment]
I think the issue occurs when the `finish` command is processed.

**Comment by jcoffland** [comment]
This should be fixed.
