### ISSUE TITLE
Display TPF so testers can calculate BC recommendations

### ISSUE THREAD

**Issue by rhavern** [FoldingAtHome/fah-client-bastet#86]
Having TPF easily available will allow internal beta testers to recommend base credit recommendations for researchers.  Thanks.

**Comment by Hou5e** [comment]
Same as web client issue: https://github.com/FoldingAtHome/fah-web-client-bastet/issues/43  😄

**Comment by jcoffland** [comment]
Completed in v8.4.0 alpha.
