### ISSUE TITLE
Time units incorrect in web display

### ISSUE THREAD

**Issue by rhavern** [FoldingAtHome/fah-client-bastet#87]
U22 v8.1.9, time was listed in "x secs y hours" but it should have been "x hours y secs" but I didn't screen shot it in time, however when it rolled over to mins/secs, it displayed as "x hours y secs" when it should have been "x mins y secs", which I did capture and attach.  Also included is the log to demonstrate that it should be mins/secs.
![Screenshot 2023-01-09 230742 v8 1 9 time units incorrect](https://user-images.githubusercontent.com/4019181/211427092-01491150-0f04-48aa-a208-ab980bd92295.png)
![Screenshot 2023-01-09 230857 v8 1 9 time units incorrect log](https://user-images.githubusercontent.com/4019181/211427111-e141e9b0-eaf8-40f3-a3e3-ea792989e51d.png)

**Comment by anand-bhat** [comment]
Fixed now per https://github.com/FoldingAtHome/fah-client-bastet/issues/26#issuecomment-1376213631
