### ISSUE TITLE
Remember finnising state through client restart

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#89]
Linux Mint 21.1 with v8.1.9:
Setting FAH to Finishing, then reboot, FAH starts paused (instead of Finishing).

Other states tested: If running before the reboot, FAH continues to run after the reboot (good).
A (finished) paused (no WU) resource group stays paused after a reboot (good).

**Comment by kbernhagen** [comment]
This is true on all platforms. 
The finish flag is not currently stored in the database.

**Comment by kbernhagen** [comment]
This seems fixed by recent commit https://github.com/FoldingAtHome/fah-client-bastet/commit/0f661cd55f8f73edcc23f30f23ab61563a5793e8

Please confirm.

**Comment by Hou5e** [comment]
I tested this once today, and it looks like it's working as expected.
