### ISSUE TITLE
Support pause on battery

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#90]
I think the `OS` object should cache battery info obtained from cbang `PowerManagement`.

If there is a performance issue, battery notifications could be used in `*OSImpl` subclasses, as needed.

The periodic `OS::update()` could check battery changes after it checks system idle for change. Maybe have a protected `virtual bool OS::checkBatteryChanged()`.

Elsewhere, the client could just use `bool OS::isOnBattery()`.

**Comment by jcoffland** [comment]
Complete in v8.3.2
