### ISSUE TITLE
Rotate log periodically

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#92]
Enhancement: Limit the console text (in the command line window) and log file size at an interval (something like: 50k or 100k lines, or once a week). At that interval, start a new log file (rotate the log in the logs folder) and clear the console text, to let FAH start over with less overhead. Or, potentially only write to the log file at an interval and not use the console to output normal logging messages.

It seems like FAH starts slowing down a few percent performance-wise after 3-7 days on higher performance multi-GPU PCs (doing 30+ WUs / day), where there is a lot more logging activity happening. This is what it feels like to me, but I don't have any real proof. 😄

**Comment by kbernhagen** [comment]
There is log-rotate-period, but the default is 0.

**Comment by jcoffland** [comment]
Really, fah-web-client-bastet needs to be improved so that it can handle larger log files with out bogging down.

**Comment by Hou5e** [comment]
I'm only running FAH without a web browser running most of the time, on the dedicated Linux Folding PCs. It seems like fah-client-bastet needs to stop using the console to output logging messages, and only keep the log in RAM to write out the log to disk periodically or send the log info to the web client when it's open. If you do keep using the console logging output, then clearing it at 50k lines automatically would help reduce the burden of it being stored in the console window over time.

**Comment by jcoffland** [comment]
Are you saying that it's your console software that is getting overloaded?  If so, that's a problem with the console software.  I don't have that problem on my Linux box using ``Terminator``, even with unlimited history enabled.

**Comment by Hou5e** [comment]
Yes, that is what it seems like. FAH seems slightly faster for the first few days and slows down over time, but doesn't get a lot slower. I'm currently just using the default built-in `terminal` command line window. This was just an observation, and might not be a real issue. It's hard to tell without running the same WU now and 2 weeks from now, to see if there is a real difference once there is 100k lines in the terminal window. When FAH runs as a service on Linux, it might be better or different (I haven't been doing this yet, only on 1 PC).

**Comment by kbernhagen** [comment]
There is an issue with the log quickly becoming huge when running a debug build with verbosity 4+. The client also becomes unresponsive when doing up/downloads with such, as every little data transfer chunk is logged.

**Comment by Hou5e** [comment]
These are the 2 changes to the default FAH options in cbang I'm suggesting (untested):

1. Option:
```
  log-to-screen <boolean=true>
    Log to screen.
```
https://github.com/CauldronDevelopmentLLC/cbang/blob/1f108404084dfa81521efa8ec2ac094d9ba7d3c3/src/cbang/log/Logger.h#L102

Change from true, to this (or just 'false' by default):
```
#ifdef DEBUG
    bool logToScreen = true;
#else
    bool logToScreen = false;
#endif
```

2. Option:
```
  log-rotate-period <integer=0>
    Rotate log once every so many seconds. No periodic rotation is performed if
    zero.
```
https://github.com/CauldronDevelopmentLLC/cbang/blob/1f108404084dfa81521efa8ec2ac094d9ba7d3c3/src/cbang/log/Logger.h#L108

Change from 0, to 5 days (432000):
```
    uint32_t logRotatePeriod = 432000;
```

I'm passing these as command line options to test this, but it will be another few days before I'll see any difference.
Differences from what I wrote: I'm using logRotatePeriod set to 1 day, and I'm running FAH as a service on Linux this time for v8.1.11.

**Comment by jcoffland** [comment]
I don't want to turn log to screen off in debug mode by default.  I use this all the time.  Anyone can turn it off on their own.  I believe you may have a special problem that is due to your terminal software.  There's no reason why a Linux program cannot output as many log lines as it likes (well maybe not 1M/sec) without slowing the system in any appreciable way.

I do agree with defaulting the rotation period but then we should probably also increase the number of old logs that are kept.

**Comment by Hou5e** [comment]
OK, I'm fine with whatever works best for you.
I was hoping this would work for Debugging normally, and disabling the logging to screen for Release mode, but I didn't compile it to see how it is setup.
```
#ifdef DEBUG
    bool logToScreen = true;
#else
    bool logToScreen = false;
#endif
```

**Comment by jcoffland** [comment]
The way to do it would be in ``fah-client/App::App()`` like this:

```c++
  options["log-to-screen"].setDefault(!(DEBUG));
```

C! is used by a lot of other software.

**Comment by Hou5e** [comment]
It looks like my suggested settings change helped slow down the PPD droop over the initial 4-6 days after re-starting FAH.
FAH v8.1.10 (without the settings), versus v8.1.11 (with: `log-to-screen=false`, `log-rotate-period=86400`, and running as a service on Linux):
![image](https://user-images.githubusercontent.com/20870053/213983551-de894b67-b5bb-4b95-8b4f-a9f468fa120e.png)
Obviously WUs vary, but I've noticed this a fair number of times: where the initial PPD is higher, and droops over time.

The daily log file size is about 1MB per day with (2) high-end video cards in a PC.
I normally only restart FAH once every 3-9 months when the power or internet service goes out.

**Comment by jcoffland** [comment]
Can you see if either ``fah-client`` or some other process is consuming a large amount of CPU or memory after running for a couple of days with out your settings changes?  You can use the ``top`` command in Linux.  ``top`` sorts processes by current CPU usage by default.  If you press SHIFT-M it will sort by memory usage.  There must be something else going on here because a large log file, on its own, shouldn't cause such a problem.

**Comment by Hou5e** [comment]
The dedicated Linux FAH PCs I'm running are (8) decent workstation-class PCs (16GB RAM, 3.6GHz 6C12T 40-lane PCIe CPU, 128-256GB M.2 PCIe3.0x4 SSD), with 1-2 Nvidia GPUs that only do GPU Folding.

I ended up restarting FAH with a different setting today for this next week to try 'verbosity=0' (like the --quiet setting says it does). I would like to see if that helps prevent the PPD droop from happening. I'll try taking a screenshot of the top command today and at the end of the week to see if I can see a difference (then I'll probably try without those FAH settings for the top command).

**Comment by jcoffland** [comment]
That would be awesome.  Thank you!

**Comment by Hou5e** [comment]
What I seem to have observed with the top command is: about a 1-2GB decrease in available RAM after a few days (with or without special settings). These screen shots are from FAH v8.1.11 (first ones with special settings, and lower ones with normal logging settings).

It turned out that I had 2 PCs with only 8GB of RAM (which seemed good enough with FAH v7). Those 2 PCs were probably contributing to some of the PPD droop, since they were potentially using swap. Before and after images for each PC:

8GB, [~11 days], special settings: verbose=0, log-to-screen=false, log-rotate-period=86400:
![image](https://user-images.githubusercontent.com/20870053/216889820-2fee958c-df96-4ae8-b9a2-f53c268f2242.png)

8GB, [~11 days], special settings: verbose=0, log-to-screen=false, log-rotate-period=86400:
![image](https://user-images.githubusercontent.com/20870053/216890643-8d4b161f-9240-4bd0-9d7d-cd50b92d7f80.png)

16GB, [~14 days], special settings: verbose=0, log-to-screen=false, log-rotate-period=86400:
![image](https://user-images.githubusercontent.com/20870053/216895055-6949d504-1faf-4ccc-a5c6-1ed382a591a8.png)

PC upgraded to 16GB RAM, [~3 days], normal settings:
![image](https://user-images.githubusercontent.com/20870053/216900743-6cf69c5c-c464-4dc1-a7e7-5b5d346f823d.png)

PC upgraded to 16GB RAM, [~3 days], normal settings:
![image](https://user-images.githubusercontent.com/20870053/216901521-67c159b9-6ee6-46ec-8341-3da99d8b3685.png)

32GB RAM, [~3 days], normal settings:
![image](https://user-images.githubusercontent.com/20870053/216903069-e5313084-896b-408b-8f4d-e8dc9f953353.png)

FAH v7 for comparison, 16GB, [~4 & ~7 days], normal settings: 
![image](https://user-images.githubusercontent.com/20870053/216898435-1aaa88fd-9b61-4eda-9a18-eb1b054678e1.png)


Someone with 64GB of RAM or more probably won't notice this quickly. 😄 
--
Different metric, from someone on Discord:
Nvidia 4090, FAH v7:
18447 ~14m PPD
18913 ~19m PPD
18601 ~28m PPD

Nvidia 4090, FAH v8 (from viewer estimate):
18447 ~12m PPD
18913 ~15m PPD
18601 ~25m PPD
He also noted the amount of time to do FAH v8 WUs is a few minutes longer.

**Comment by jcoffland** [comment]
The log now rotates once per day.
