### ISSUE TITLE
Update Windows system tray app `About` form

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#94]
Update Windows system tray app `About` form (v8.1.9):
![image](https://user-images.githubusercontent.com/20870053/211999665-66ff8a93-2915-4296-acd2-e56561fdda34.png)

**Comment by kbernhagen** [comment]
Is WinOSImpl created before `Application::init()` occurs?

**Comment by jcoffland** [comment]
> Is WinOSImpl created before `Application::init()` occurs?

Yes

**Comment by jcoffland** [comment]
Fixed in v8.1.10

**Comment by kbernhagen** [comment]
I think this was fixed in v8.1.11
