### ISSUE TITLE
Windows system tray app `Pause` only functions as a status indicator

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#96]
In the Windows system tray app menu, the `Pause` item only works as a status indicator. Clicking on it doesn't start or pause folding like you would expect. If it wasn't intended to be a control, then labeling it as 'Pause [Status]' and making it look disabled, would be better.
![image](https://user-images.githubusercontent.com/20870053/212466658-6d7b4f06-0715-42da-af20-e3456f936a49.png)

**Comment by kbernhagen** [comment]
It's definitely supposed to toggle paused.

It might take a second or two to update, and maybe won't update while the menu is displayed.

**Comment by Hou5e** [comment]
When I click on Pause in the menu, the popup menu disappears and FAH does nothing. If FAH was paused, then it stays that way. You can watch the web interface and see Folding is not starting. It's like togglePaused isn't working on Windows: https://github.com/FoldingAtHome/fah-client-bastet/blob/bb450b693fbcc5d1bfd147c768667637d5aebf7e/src/fah/client/OS.cpp#L85-L89

**Comment by kbernhagen** [comment]
That might need to be “->add(0);”

**Comment by kbernhagen** [comment]
It looks like `cb::Event::add()` passes a NULL `struct timeval *` to `event_add()`, which seems like it then ignores the call.

Maybe cbang Event should have
```cpp
void Event::add() {
  static struct timeval tv = {0};
  event_add(e, &tv);
  if (selfReferencing) self = this; // Don't deallocate while scheduled
}
```

**Comment by jcoffland** [comment]
Plain ``Event::add()`` is for adding non-timed events, like read and write events which are tied to a file descriptor.  It should be ``add(0)`` as suggested.
